/*****V73.07-V73.08 END*/
DELIMITER  $
DROP PROCEDURE IF EXISTS `LF_PVERV0`$

CREATE DEFINER=`root`@`%`  PROCEDURE `LF_PVERV0`(
    DBVERSIONSTR VARCHAR(32),
    NUM INT,
    TOTALSTR INT
)
BEGIN
    IF EXISTS(SELECT * FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR) THEN
      DELETE FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR;
    END IF;
END    $

CALL LF_PVERV0('73.10',1,1)$
DROP PROCEDURE IF EXISTS `LF_PVERV0`$

/*网关升级脚本 START*/
/*网关升级脚本 END*/

/*WEB升级脚本 START*/

DELIMITER $
DROP PROCEDURE IF EXISTS `DELETEPROCEDURE`$
CREATE  DEFINER=`root`@`%`  PROCEDURE `DELETEPROCEDURE`()
BEGIN
-- 删除是否检查运营商余额的配置项
IF  EXISTS (SELECT * FROM LF_GLOBAL_VARIABLE WHERE GLOBALID=601 AND GLOBALKEY='GWFEE_CHECK')
THEN
DELETE FROM  LF_GLOBAL_VARIABLE WHERE GLOBALID=601 AND GLOBALKEY='GWFEE_CHECK';
END IF;


-- 删除登录页面是否需要验证码的配置项
IF  EXISTS (SELECT * FROM LF_SYS_PARAM WHERE PARAM_ITEM = 'loginYanZhengMa')
THEN
DELETE FROM  LF_SYS_PARAM  WHERE PARAM_ITEM = 'loginYanZhengMa';
END IF;


-- 删除系统下行记录导出的最大记录条数配置项
IF  EXISTS(SELECT * FROM LF_SYS_PARAM WHERE PARAM_ITEM = 'cxtjMtExportLimit')
THEN
DELETE FROM  LF_SYS_PARAM WHERE PARAM_ITEM = 'cxtjMtExportLimit';
END IF;

-- 删除web运行参数页面的查看权限
IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=1 AND PRIVILEGE_ID=3595)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=1 AND PRIVILEGE_ID=3595;
END IF;

IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=2 AND PRIVILEGE_ID=3595)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=2 AND PRIVILEGE_ID=3595;
END IF;

IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=4 AND PRIVILEGE_ID=3595)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=4 AND PRIVILEGE_ID=3595;
END IF;

-- 删除WEB运行参数配置页面菜单
IF  EXISTS (SELECT * FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = 3595)
THEN
DELETE FROM  LF_PRIVILEGE WHERE PRIVILEGE_ID = 3595;
END IF;

-- 删除群发历史查询汇总权限
IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=1 AND PRIVILEGE_ID=7009)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=1 AND PRIVILEGE_ID=7009;
END IF;

IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=2 AND PRIVILEGE_ID=7009)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=2 AND PRIVILEGE_ID=7009;
END IF;

IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=4 AND PRIVILEGE_ID=7009)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=4 AND PRIVILEGE_ID=7009;
END IF;

-- 删除群发历史查询汇总菜单
IF  EXISTS (SELECT * FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = 7009)
THEN
DELETE FROM  LF_PRIVILEGE WHERE PRIVILEGE_ID = 7009;
END IF;


-- 删除汇总转移日志权限
IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=1 AND PRIVILEGE_ID=3594)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=1 AND PRIVILEGE_ID=3594;
END IF;

IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=2 AND PRIVILEGE_ID=3594)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=2 AND PRIVILEGE_ID=3594;
END IF;

IF  EXISTS(SELECT * FROM LF_IMPOWER WHERE ROLE_ID=4 AND PRIVILEGE_ID=3594)
THEN
DELETE FROM LF_IMPOWER WHERE ROLE_ID=4 AND PRIVILEGE_ID=3594;
END IF;

-- 删除汇总转移日志菜单
IF  EXISTS (SELECT * FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = 3594)
THEN
DELETE FROM  LF_PRIVILEGE WHERE PRIVILEGE_ID = 3594;
END IF;

-- HTTP请求超时时间(毫秒)  发送HTTP请求超时时间，由150秒改成120秒 ------------
UPDATE LF_GLOBAL_VARIABLE SET GLOBALVALUE=120000 WHERE GLOBALID=44 AND GLOBALKEY='HTTP_REQUEST_TIMEOUT';
-- HTTP响应超时时间(毫秒)  发送HTTP请求超时时间，由150秒改成120秒 ------------
UPDATE LF_GLOBAL_VARIABLE SET GLOBALVALUE=120000 WHERE GLOBALID=45 AND GLOBALKEY='HTTP_RESPONSE_TIMEOUT';

END $
CALL `DELETEPROCEDURE`$
DROP PROCEDURE IF EXISTS `DELETEPROCEDURE`$

/*WEB升级脚本 END*/

DROP PROCEDURE IF EXISTS `LF_PVERV0`$

CREATE DEFINER=`root`@`%` PROCEDURE `LF_PVERV0`(
    VERSIONSTR VARCHAR(32),
    DBVERSIONSTR VARCHAR(32),
    WBSVERSION VARCHAR(32),
    SPGATEVERSION VARCHAR(32),
    VERSIONSTR_OLD VARCHAR(32),
	WBSVERSION_OLD VARCHAR(32),
	SPGATEVERSION_OLD VARCHAR(32),
    NUM INT,
    TOTALSTR INT
)
BEGIN
	/*EMP产品版本记录*/
	/*EMP-WEB*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,1000,VERSIONSTR,NOW(),NOW(),'EMP-WEB');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=VERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
	END IF;
	/*EMP_GATEWAY*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,2000,WBSVERSION,NOW(),NOW(),'EMP_GATEWAY');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=WBSVERSION WHERE  PRODUCT_ID=1000 AND PROCESS_ID=2000;
	END IF;
	/*SMT_SPGATE*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,3000,SPGATEVERSION,NOW(),NOW(),'SMT_SPGATE');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=SPGATEVERSION WHERE  PRODUCT_ID=1000 AND PROCESS_ID=3000;
	END IF;
	/*EMP产品版本历史记录*/
	/*EMP-WEB*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
			INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO,ISRELEASE,VERSIONINFO)
			VALUES(1000,1000,VERSIONSTR,NOW(),NOW(),'EMP-WEB',1,'1.修复由于百分号转义产生的内容错误问题;<br>2.修复 客服短信-》客户群组群发-》：发送内容输入半角单引号，提交发送之后在群发任务查看内容没有单引号 的问题;<br>3.修复 移动客服-》客户群组群发-》：发送特殊字符，会缺失或替换 的问题；<br>4.修复 参数内容包含中文，在群发任务查看发出的内容是乱码 的问题；<br>5.修复fastjson漏洞；<br>6.修复 操作员在绑定接入账号后，在SP账号统计报表查询不到接入账号数据 的问题；<br>7.解决客户群组群发''''\''字符串转成\的问题；<br>8.解决发送人民币符号变问号的问题。');
	ELSE
			UPDATE LF_VERSION_HIS SET UPDATETIME=NOW(),ISRELEASE=1,VERSIONINFO='1.修复由于百分号转义产生的内容错误问题;<br>2.修复 客服短信-》客户群组群发-》：发送内容输入半角单引号，提交发送之后在群发任务查看内容没有单引号 的问题;<br>3.修复 移动客服-》客户群组群发-》：发送特殊字符，会缺失或替换 的问题；<br>4.修复 参数内容包含中文，在群发任务查看发出的内容是乱码 的问题；<br>5.修复fastjson漏洞；<br>6.修复 操作员在绑定接入账号后，在SP账号统计报表查询不到接入账号数据 的问题；<br>7.解决客户群组群发''''\''字符串转成\的问题；<br>8.解决发送人民币符号变问号的问题。' WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
	END IF;
    /*删除web旧版本历史*/
    IF EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
        DELETE FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
    END IF;
	IF EXISTS(SELECT * FROM LF_VERSION WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
        DELETE FROM LF_VERSION WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
    END IF;
	
	-- 删除旧版本EMP_GATEWAY历史记录
    IF EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000)
    THEN
      DELETE FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
    END IF;
	IF EXISTS(SELECT * FROM LF_VERSION WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000)
    THEN
      DELETE FROM LF_VERSION WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
    END IF;
	
	-- 删除旧版本SMT_SPGATE历史记录
    IF EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000)
    THEN
      DELETE FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
    END IF;
	IF EXISTS(SELECT * FROM LF_VERSION WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000)
    THEN
      DELETE FROM LF_VERSION WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
    END IF;
	
	/*EMP_GATEWAY*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION AND PRODUCT_ID=1000 AND PROCESS_ID=2000) THEN
		INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,2000,WBSVERSION,NOW(),NOW(),'EMP_GATEWAY');
	ELSE
		UPDATE LF_VERSION_HIS SET UPDATETIME=NOW() WHERE  PRODUCT_ID=1000 AND PROCESS_ID=2000;
	END IF;
	/*SMT_SPGATE*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION AND PRODUCT_ID=1000 AND PROCESS_ID=3000) THEN
		INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,3000,SPGATEVERSION,NOW(),NOW(),'SMT_SPGATE');
	ELSE
		UPDATE LF_VERSION_HIS SET UPDATETIME=NOW() WHERE  PRODUCT_ID=1000 AND PROCESS_ID=3000;
	END IF;
	IF NOT EXISTS(SELECT * FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR AND CURRENT_NO=NUM AND TOTAL=TOTALSTR) THEN
		/*EMP产品数据库版本信息表*/
		INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
		VALUES(DBVERSIONSTR,NOW(),NOW(),NUM,TOTALSTR,2,'1号脚本');
	ELSE
		UPDATE LF_DB_SCRIPT SET STATE=2,UPDATETIME=NOW() WHERE  CURRENT_NO=NUM AND TOTAL=TOTALSTR;
	END IF;
END     $
CALL LF_PVERV0('7.3.9.645.SP9','73.09','8.6.5.220','6.1.53.345','7.3.10.667.SP10','8.6.5.220','6.1.53.345',1,1)$
DROP PROCEDURE IF EXISTS `LF_PVERV0`$
/*****V73.07-V73.08 END*/