-----------V73.07-V73.08 START------------------------
DECLARE COUNTNUM INT;
        DBVERSIONSTR VARCHAR2(32);
        NUMNO INT;
        TOTALINT INT;
BEGIN
  DBVERSIONSTR:='73.09';
  NUMNO:=1;
  TOTALINT:=1;
  SELECT COUNT(*) INTO COUNTNUM FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR;
  IF COUNTNUM>0 THEN
    DELETE FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR;
    COMMIT;
  END IF;
END;
/
/*网关升级脚本 START*/
/*网关升级脚本 END*/

/*WEB升级脚本 START*/
/*WEB升级脚本 END*/

--增加版本信息--
DECLARE COUNTNUM INT;
        VERSIONSTR VARCHAR2(32);
        DBVERSIONSTR VARCHAR2(32);
        WBSVERSIONSTR VARCHAR2(32);
        SPGATEVERSIONSTR VARCHAR2(32);
        VERSIONSTR_OLD VARCHAR2(32);
		WBSVERSION_OLD VARCHAR(32);
	    SPGATEVERSION_OLD VARCHAR(32);
        NUMNO INT;
        TOTALINT INT;
BEGIN
    VERSIONSTR:='7.3.8.612.SP8';
    DBVERSIONSTR:='73.08';
    WBSVERSIONSTR:='8.6.4.219';
    SPGATEVERSIONSTR:='6.1.52.344';
    VERSIONSTR_OLD:='7.3.9.645.SP9';
	WBSVERSION_OLD:='8.6.5.220';
	SPGATEVERSION_OLD:='6.1.53.345';
	
  NUMNO:=1;
  TOTALINT:=1;
  --EMP产品版本记录
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
  IF COUNTNUM=0 THEN
   --EMP-WEB
   INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
   VALUES(1000,1000,VERSIONSTR,SYSDATE,SYSDATE,'EMP-WEB');
  ELSE
    UPDATE LF_VERSION SET UPDATETIME=SYSDATE,VERSION=VERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
  END IF;
  COMMIT;
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000;
  IF COUNTNUM=0 THEN
   --EMP_GATEWARY
   INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
   VALUES(1000,2000,WBSVERSIONSTR,SYSDATE,SYSDATE,'EMP_GATEWARY');
  ELSE
    UPDATE LF_VERSION SET UPDATETIME=SYSDATE,VERSION=WBSVERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000;
  END IF;
  COMMIT;
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000;
  IF COUNTNUM=0 THEN
   --SMT_SPGATE
   INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
   VALUES(1000,3000,SPGATEVERSIONSTR,SYSDATE,SYSDATE,'SMT_SPGATE');
  ELSE
    UPDATE LF_VERSION SET UPDATETIME=SYSDATE,VERSION=SPGATEVERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000;
  END IF;
  COMMIT;
  --EMP产品版本历史记录
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
  IF COUNTNUM=0 THEN
    --EMP-WEB
    INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO,ISRELEASE,VERSIONINFO)
    VALUES(1000,1000,VERSIONSTR,SYSDATE,SYSDATE,'EMP-WEB',1,'1.修复群发任务查看修改定时任务时，提示发送内容不能为空，导致不能修改定时任务的问题<br/>2.修复状态码导入模板时出错的时候，会闪现多个dialog框的问题<br/>3.查询统计-数据查询-自定参数统计报表，选择时间区间为同一天时间查询，无法查询出数据，实际当天有数据<br/>4.查询统计-统计报表，运营商/SP账号/机构/操作员/业务类型/区域报表，查询统计-数据分析，总体发送趋势，短信类型应为信息类型<br/>5.解决插入操作日志表超时的问题<br/>6.解决V73.00 Oracle全新脚本mt_datareport表缺少recfail字段<br/>7.解决查询统计-统计报表-区域统计报表模块，oracle/db2环境查询报错');
  ELSE
    UPDATE LF_VERSION_HIS SET UPDATETIME=SYSDATE,ISRELEASE=1,VERSIONINFO='1.修复群发任务查看修改定时任务时，提示发送内容不能为空，导致不能修改定时任务的问题<br/>2.修复状态码导入模板时出错的时候，会闪现多个dialog框的问题<br/>3.查询统计-数据查询-自定参数统计报表，选择时间区间为同一天时间查询，无法查询出数据，实际当天有数据<br/>4.查询统计-统计报表，运营商/SP账号/机构/操作员/业务类型/区域报表，查询统计-数据分析，总体发送趋势，短信类型应为信息类型<br/>5.解决插入操作日志表超时的问题<br/>6.解决V73.00 Oracle全新脚本mt_datareport表缺少recfail字段<br/>7.解决查询统计-统计报表-区域统计报表模块，oracle/db2环境查询报错' WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
  END IF;
  COMMIT;
    --删除EMP旧版本信息
    SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
    IF COUNTNUM>0 THEN
        --EMP-WEB
    DELETE FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
    END IF;
    COMMIT;
	SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
    IF COUNTNUM>0 THEN
        --EMP-WEB
    DELETE FROM LF_VERSION WHERE VERSION=VERSIONSTR_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
    END IF;
    COMMIT;
	
	
	-- 删除旧版本EMP_GATEWAY历史记录
	SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
    IF COUNTNUM>0 THEN
        --EMP_GATEWAY
    DELETE FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
    END IF;
    COMMIT;
	SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
    IF COUNTNUM>0 THEN
        --EMP_GATEWAY
    DELETE FROM LF_VERSION WHERE VERSION=WBSVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
    END IF;
    COMMIT;
	
	
	-- 删除旧版本SMT_SPGATE历史记录
	SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
    IF COUNTNUM>0 THEN
        --SMT_SPGATE
    DELETE FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
    END IF;
    COMMIT;
	SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
    IF COUNTNUM>0 THEN
        --SMT_SPGATE
    DELETE FROM LF_VERSION WHERE VERSION=SPGATEVERSION_OLD AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
    END IF;
    COMMIT;
	
	
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=WBSVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
  IF COUNTNUM=0 THEN
    --EMP_GATEWARY
    INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
    VALUES(1000,2000,WBSVERSIONSTR,SYSDATE,SYSDATE,'EMP_GATEWARY');
  ELSE
    UPDATE LF_VERSION_HIS SET UPDATETIME=SYSDATE WHERE VERSION=WBSVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
  END IF;
  COMMIT;

  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
  IF COUNTNUM=0 THEN
    --SMT_SPGATE
    INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
    VALUES(1000,3000,SPGATEVERSIONSTR,SYSDATE,SYSDATE,'SMT_SPGATE');
  ELSE
    UPDATE LF_VERSION_HIS SET UPDATETIME=SYSDATE WHERE VERSION=SPGATEVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
  END IF;
  COMMIT;

  SELECT COUNT(*) INTO COUNTNUM FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR;
  IF COUNTNUM=0 THEN
    --EMP产品数据库版本信息表
    INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
    VALUES(DBVERSIONSTR,SYSDATE,SYSDATE,NUMNO,TOTALINT,2,'WEB更改');
  ELSE
    UPDATE LF_DB_SCRIPT SET STATE=2,UPDATETIME=SYSDATE WHERE  VERSION=DBVERSIONSTR AND CURRENT_NO=NUMNO AND TOTAL=TOTALINT;
  END IF;
  COMMIT;
END;
/
--重新编译所有存储过程和触发器
CALL COMPILE_PROCEDURE();
/
