CREATE USER emp IDENTIFIED BY "123456";

GRANT RESOURCE,CONNECT,EXECUTE ANY PROCEDURE,DROP TABLESPACE,
CREATE ANY TABLE ,INSERT ANY TABLE,UPDATE ANY TABLE,DELETE ANY TABLE,UNLIMITED TABLESPACE,CREATE ANY VIEW,
DROP ANY VIEW TO emp;
