package com.montnets.emp.qyll.dao.sql;

/**
 * @author Jason Huang
 * @date 2017年12月28日 下午4:12:41
 */

public class DataQueryDB2SQL extends DataQuerySQL {
	
	/**
	 * DB2中使用FETCH FIRST 1 ROWS ONLY表示只需要一行记录
	 */
	public String getOrderTaskFiledSQL() {
		return "SELECT LL_ORDER_TASK.ID,LF_SYSUSER.NAME,(SELECT LL_ORDER_DETAIL.MSG FROM "
				+ detailTable
				+ " LL_ORDER_DETAIL WHERE LL_ORDER_TASK.ORDERNO = LL_ORDER_DETAIL.ORDERNO FETCH FIRST 1 ROWS ONLY)AS MSG,LF_DEP.DEP_NAME,LL_ORDER_TASK.ORDERNO,LL_ORDER_TASK.TOPIC,LL_ORDER_TASK.PRO_IDS,LL_ORDER_TASK.ORDERSTATUS,LL_ORDER_TASK.SMSSTATUS,LL_ORDER_TASK.CREATETM,LL_ORDER_TASK.ORDERTM,LL_ORDER_TASK.SUBCOUNT,"
				+ " (SELECT COUNT(*) FROM " + detailTable
				+ " LL_ORDER_DETAIL WHERE LL_ORDER_DETAIL.ORDERNO = LL_ORDER_TASK.ORDERNO AND LLRPT = '1') AS SUCCOUNT";
	}

}
