CREATE OR REPLACE PROCEDURE GW_LOADLFTEMPLATE
 (
  OUT_CURSOR OUT SYS_REFCURSOR
 )
AS
BEGIN
  OPEN OUT_CURSOR FOR
  SELECT TM_ID,USER_ID,TM_NAME,TM_MSG,DSFLAG,TM_STATE,ADDTIME,ISPASS,TMP_TYPE,BIZ_CODE,CORP_CODE,PARAMCNT,TM_CODE,SP_TEMPLID,DEGREE,RMSRESSIZE,H5RESSIZE,ISPUBLIC,PARAMSNUM,VER  FROM LF_TEMPLATE WHERE TM_STATE=1 AND (TMP_TYPE=3 OR TMP_TYPE=11);
END;
/

CREATE OR REPLACE PROCEDURE GW_LOAD_ECERRCODEBIND
 (
  OUT_CURSOR OUT SYS_REFCURSOR
 )
AS
BEGIN
  OPEN OUT_CURSOR FOR
  SELECT CORP_CODE,STATE_CODE,MAPPING_CODE,STATE_DES  FROM LF_STATECODE;
END;
/