-----------V6.35-V6.39 START------------------------

DECLARE TABLEEXIST NUMBER;
BEGIN 
   SELECT COUNT(1) INTO TABLEEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_ORDER_TASK') ;  --判断表是否存在
   IF TABLEEXIST = 0  THEN   --如果不存在，进行创建  
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_ORDER_TASK   
    (
      ID NUMBER(11) NOT NULL,
      TASKID NUMBER(38) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR2(36) DEFAULT '' '' NOT NULL,
      ECID VARCHAR2(16) DEFAULT '' '' NOT NULL,
      USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
      ORG_ID NUMBER(11) DEFAULT 0 NOT NULL,
      TOPIC VARCHAR2(64) DEFAULT '' '' NOT NULL,   
      PRO_IDS VARCHAR2(32) DEFAULT '' '' NOT NULL,
      MSGTYPE CHAR(1) DEFAULT ''1'' NOT NULL,
      TEMP_ID NUMBER(11) DEFAULT 0 NOT NULL,
      SP_USER VARCHAR2(32) DEFAULT '' '' NOT NULL,
      SP_PWD VARCHAR2(32) DEFAULT '' '' NOT NULL,
      SUBCOUNT NUMBER(11) DEFAULT 0 NOT NULL,  
      EFFCOUNT NUMBER(11) DEFAULT 0 NOT NULL,
      SUCCOUNT NUMBER(11) DEFAULT 0 NOT NULL,
      FAICOUNT NUMBER(11) DEFAULT 0 NOT NULL,
      TIMER_STATUS CHAR(1) DEFAULT ''1'' NOT NULL,
      TIMER_TIME TIMESTAMP DEFAULT TO_DATE(''1900-1-1 00:00:00'',''YYYY-MM-DD HH24:MI:SS'') NOT NULL,
      RE_STATUS CHAR(1) DEFAULT ''1'' NOT NULL,
      ORDERSTATUS CHAR(1) DEFAULT ''1'' NOT NULL,
      SMSSTATUS CHAR(1) DEFAULT ''1'' NOT NULL,
      ISRETRY CHAR(1) DEFAULT ''1'' NOT NULL,
      SUBMITTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      SUMMONEY NUMBER(12,2) DEFAULT 0 NOT NULL
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_TASK_USER_ID ON LL_ORDER_TASK (USER_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_TASK_ORDERTM ON LL_ORDER_TASK (ORDERTM)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_TASK_ORG_ID ON LL_ORDER_TASK (ORG_ID)';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_TASK ADD PRIMARY KEY (ID)';
    END IF ;
END;          
/


DECLARE TABLEEXIST NUMBER;
BEGIN
   SELECT COUNT(1) INTO TABLEEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_PRODUCT') ;  --判断表是否存在
   IF TABLEEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_PRODUCT
    (
      ID NUMBER(11) NOT NULL,
      ECID NUMBER(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR2(32) DEFAULT '' '' NOT NULL,
      PRODUCTNAME VARCHAR2(32) DEFAULT '' '' NOT NULL,
      ISP VARCHAR2(16) DEFAULT '' '' NOT NULL,
      VOLUME VARCHAR2(16) DEFAULT '' '' NOT NULL,
      PRICE NUMBER(11,2) DEFAULT 0 NOT NULL,
      DISCPRICE NUMBER(11,2)  DEFAULT 0 NOT NULL,
      AREA VARCHAR2(32) DEFAULT '' '' NOT NULL,
      PTYPE NUMBER(11) DEFAULT 0 NOT NULL,
      PMOLD NUMBER(11) DEFAULT 0 NOT NULL,
      RTYPE NUMBER(11) DEFAULT 0 NOT NULL,
      STATUS NUMBER(11) DEFAULT 0 NOT NULL,
      UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      OPERATORID NUMBER(11) DEFAULT 0 NOT NULL    
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_PRO_PRODUCTID ON  LL_PRODUCT (PRODUCTID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_PRO_PRODUCTNAME ON LL_PRODUCT (PRODUCTNAME)';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_PRODUCT ADD PRIMARY KEY (ID)';
    END IF ;
END;     
/


DECLARE TABLEEXIST NUMBER;
BEGIN
   SELECT COUNT(1) INTO TABLEEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_COMP_INFO') ;  --判断表是否存在
   IF TABLEEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_COMP_INFO
    (
      ID NUMBER(11) NOT NULL,
      LLACCOUNT VARCHAR2(64) DEFAULT '' '' NOT NULL,
      PASSWORD VARCHAR2(64) DEFAULT '' '' NOT NULL,
      ECID NUMBER(11) DEFAULT 0 NOT NULL,
      ECNAME VARCHAR2(32) DEFAULT '' '' NOT NULL,
      IP VARCHAR2(32) DEFAULT '' '' NOT NULL,
      PORT NUMBER(11) DEFAULT 0 NOT NULL,
      REMARK VARCHAR2(1024) DEFAULT '' '' NOT NULL,
      UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATEID NUMBER(11) DEFAULT 0 NOT NULL,
      UPDATEID NUMBER(11) DEFAULT 0 NOT NULL,
      PUSHADDR VARCHAR2(128) DEFAULT '' '' NOT NULL
    )';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_COMP_INFO ADD PRIMARY KEY (ID)';
    END IF ;
END;    
/


DECLARE TEXIST NUMBER;
BEGIN
   SELECT COUNT(1) INTO TEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_ORDER_DETAIL') ;  --判断表是否存在
   IF TEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_ORDER_DETAIL
    (
      ID  NUMBER(11) NOT NULL,
      MOBILE VARCHAR2(16) DEFAULT '' '' NOT NULL,
      MSG VARCHAR2(2048) DEFAULT '' '' NOT NULL,
      BATCHID NUMBER(11) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR2(64) DEFAULT '' '' NOT NULL,
      LLRPT VARCHAR2(32) DEFAULT '' '' NOT NULL,
	  ERRCODE VARCHAR2(20) DEFAULT '' '' NOT NULL,
      USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
      ORG_ID  NUMBER(11) DEFAULT 0 NOT NULL,
      PRO_ID NUMBER(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR2(32) DEFAULT '' '' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      RPTTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      STATUS	NUMBER(11) DEFAULT 0 NOT NULL
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_MOBILE ON LL_ORDER_DETAIL (MOBILE)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERNO ON LL_ORDER_DETAIL (ORDERNO)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_USER_ID ON LL_ORDER_DETAIL (USER_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORG_ID ON LL_ORDER_DETAIL (ORG_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_PRO_ID ON LL_ORDER_DETAIL (PRO_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERTM ON LL_ORDER_DETAIL (ORDERTM)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_LLPRT ON LL_ORDER_DETAIL (LLRPT)';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_DETAIL ADD PRIMARY KEY (ID)';
    END IF ;
END;    
/

DECLARE TEXIST NUMBER;
BEGIN
   SELECT COUNT(1) INTO TEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_ORDER_DETAIL2017') ;  --判断表是否存在
   IF TEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_ORDER_DETAIL2017
    (
      ID  NUMBER(11) NOT NULL,
      MOBILE VARCHAR2(16) DEFAULT '' '' NOT NULL,
      MSG VARCHAR2(2048) DEFAULT '' '' NOT NULL,
      BATCHID NUMBER(11) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR2(64) DEFAULT '' '' NOT NULL,
      LLRPT VARCHAR2(32) DEFAULT '' '' NOT NULL,
      ERRCODE VARCHAR2(20) DEFAULT '' '' NOT NULL,
      USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
      ORG_ID  NUMBER(11) DEFAULT 0 NOT NULL,
      PRO_ID NUMBER(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR2(32) DEFAULT '' '' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      RPTTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      STATUS	NUMBER(11) DEFAULT 0 NOT NULL
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_MOBILE2017 ON LL_ORDER_DETAIL2017 (MOBILE)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERNO2017 ON LL_ORDER_DETAIL2017 (ORDERNO)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_USER_ID2017 ON LL_ORDER_DETAIL2017 (USER_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORG_ID2017 ON LL_ORDER_DETAIL2017 (ORG_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_PRO_ID2017 ON LL_ORDER_DETAIL2017 (PRO_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERTM2017 ON LL_ORDER_DETAIL2017 (ORDERTM)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_LLPRT2017 ON LL_ORDER_DETAIL2017 (LLRPT)';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_DETAIL2017 ADD PRIMARY KEY (ID)';
    END IF ;
END;    
/

DECLARE TEXIST NUMBER;
BEGIN
   SELECT COUNT(1) INTO TEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_ORDER_DETAIL2018') ;  --判断表是否存在
   IF TEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_ORDER_DETAIL2018
    (
      ID  NUMBER(11) NOT NULL,
      MOBILE VARCHAR2(16) DEFAULT '' '' NOT NULL,
      MSG VARCHAR2(2048) DEFAULT '' '' NOT NULL,
      BATCHID NUMBER(11) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR2(64) DEFAULT '' '' NOT NULL,
      LLRPT VARCHAR2(32) DEFAULT '' '' NOT NULL,
      ERRCODE VARCHAR2(20) DEFAULT '' '' NOT NULL,
      USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
      ORG_ID  NUMBER(11) DEFAULT 0 NOT NULL,
      PRO_ID NUMBER(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR2(32) DEFAULT '' '' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      RPTTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      STATUS	NUMBER(11) DEFAULT 0 NOT NULL
    )';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_MOBILE2018 ON LL_ORDER_DETAIL2018 (MOBILE)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERNO2018 ON LL_ORDER_DETAIL2018 (ORDERNO)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_USER_ID2018 ON LL_ORDER_DETAIL2018 (USER_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORG_ID2018 ON LL_ORDER_DETAIL2018 (ORG_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_PRO_ID2018 ON LL_ORDER_DETAIL2018 (PRO_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERTM2018 ON LL_ORDER_DETAIL2018 (ORDERTM)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_LLPRT2018 ON LL_ORDER_DETAIL2018 (LLRPT)';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_DETAIL2018 ADD PRIMARY KEY (ID)';
    END IF ;
END;    
/
DECLARE TABLEEXIST NUMBER;
BEGIN
   SELECT COUNT(1) INTO TABLEEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_DATA_REPORT') ;  --判断表是否存在
   IF TABLEEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_DATA_REPORT
    (
      ID  NUMBER(11) NOT NULL,
      PRO_ID VARCHAR2(16) DEFAULT '' '' NOT NULL,
      USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
      ORG_ID  NUMBER(11) DEFAULT 0 NOT NULL,
      ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
      SUNMITNUM NUMBER(11) DEFAULT 0 NOT NULL,
      SUCCNUM NUMBER(11) DEFAULT 0 NOT NULL,
      FAILDNUM  NUMBER(11) DEFAULT 0 NOT NULL,
      R1  VARCHAR2(64) DEFAULT '' '' NOT NULL,
      R2  VARCHAR2(64) DEFAULT '' '' NOT NULL,
      R3  VARCHAR2(64) DEFAULT '' '' NOT NULL,
      R4  VARCHAR2(64) DEFAULT '' '' NOT NULL,
      CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL
    )';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_DATA_REPORT  ADD PRIMARY KEY (PRO_ID,USER_ID,ORDERTM)';
    END IF ;
END;    
/


DECLARE 
    TABLEEXIST NUMBER;   
BEGIN
   SELECT COUNT(1) INTO TABLEEXIST FROM USER_TABLES WHERE TABLE_NAME=UPPER('LL_STATUSRPT'); --判断表是否存在
   IF TABLEEXIST = 0  THEN   --如果不存在，进行创建
      EXECUTE IMMEDIATE  
    'CREATE TABLE LL_STATUSRPT
    (
        ID  NUMBER(11) NOT NULL,
        MOBILE  VARCHAR(16) DEFAULT '' '' NOT NULL,           
        PRODUCTID  VARCHAR2(32) DEFAULT '' '' NOT NULL,
        LLRPT      VARCHAR2(2) DEFAULT '' '' NOT NULL,
        ORDERTM    VARCHAR2(16) DEFAULT '' '' NOT NULL,
        ERRCODE    VARCHAR2(16) DEFAULT '' '' NOT NULL,
        ORDERNO    VARCHAR2(64) DEFAULT '' '' NOT NULL,
        CREATETM   TIMESTAMP DEFAULT SYSDATE NOT NULL
    )';
    EXECUTE IMMEDIATE 'ALTER TABLE LL_STATUSRPT ADD PRIMARY KEY (ID)';
    END IF ;
END;
/


DECLARE
  VERSION INT;
BEGIN
  SELECT COUNT(*) INTO VERSION FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_LL_PRODUCT';
  IF VERSION = 0 THEN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LL_PRODUCT
      MINVALUE 1        
      NOMAXVALUE       
      START WITH 1      
      INCREMENT BY 1    
      NOCYCLE           
      NOCACHE';
END IF;
END;
/

DECLARE
  VERSION INT;
BEGIN
  SELECT COUNT(*) INTO VERSION FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_LL_ORDER_TASK';
  IF VERSION = 0 THEN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LL_ORDER_TASK
      MINVALUE 1       
      NOMAXVALUE        
      START WITH 1      
      INCREMENT BY 1    
      NOCYCLE           
      NOCACHE';
END IF;
END;
/
          

DECLARE
  VERSION INT;
BEGIN
  SELECT COUNT(*) INTO VERSION FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_LL_ORDER_DETAIL';
  IF VERSION = 0 THEN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LL_ORDER_DETAIL
      MINVALUE 1       
      NOMAXVALUE       
      START WITH 1    
      INCREMENT BY 1  
      NOCYCLE          
      NOCACHE';     
END IF;
END;
/



DECLARE
  VERSION INT;
BEGIN
  SELECT COUNT(*) INTO VERSION FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_LL_PRODUCT';
  IF VERSION = 0 THEN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LL_PRODUCT
    MINVALUE 1        
    NOMAXVALUE       
    START WITH 1     
    INCREMENT BY 1    
    NOCYCLE          
    NOCACHE';
END IF;
END;
/

DECLARE
  VERSION INT;
BEGIN
  SELECT COUNT(*) INTO VERSION FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_LL_STATUSRPT';
  IF VERSION = 0 THEN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LL_STATUSRPT
    MINVALUE 1       
    NOMAXVALUE       
    START WITH 1     
    INCREMENT BY 1    
    NOCYCLE         
    NOCACHE';
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_THIR_MENUCONTROL WHERE MENU_NUM=28;
IF VERSION = 0 THEN
	INSERT INTO LF_THIR_MENUCONTROL(TID, MENU_NUM, TITLE, PRI_MENU, PRI_ORDER) VALUES(S_LF_THIR_MENUCONTROL.NEXTVAL, 28,'企业流量',88,1600);
	INSERT INTO LF_THIR_MENUCONTROL(TID, MENU_NUM, TITLE, PRI_MENU, PRI_ORDER) VALUES(S_LF_THIR_MENUCONTROL.NEXTVAL,28,'企业流量',89,1700);
	INSERT INTO LF_THIR_MENUCONTROL(TID, MENU_NUM, TITLE, PRI_MENU, PRI_ORDER) VALUES(S_LF_THIR_MENUCONTROL.NEXTVAL,28,'企业流量',90,1800);
	INSERT INTO LF_THIR_MENUCONTROL(TID, MENU_NUM, TITLE, PRI_MENU, PRI_ORDER) VALUES(S_LF_THIR_MENUCONTROL.NEXTVAL,28,'企业流量',91,1900);
END IF;
END;
/

UPDATE LF_THIR_MENUCONTROL SET PRI_ORDER = 370 WHERE MENU_NUM = 28 AND PRI_MENU = 88;
UPDATE LF_THIR_MENUCONTROL SET PRI_ORDER = 375 WHERE MENU_NUM = 28 AND PRI_MENU = 89;
UPDATE LF_THIR_MENUCONTROL SET PRI_ORDER = 380 WHERE MENU_NUM = 28 AND PRI_MENU = 90;
UPDATE LF_THIR_MENUCONTROL SET PRI_ORDER = 385 WHERE MENU_NUM = 28 AND PRI_MENU = 91;

COMMIT;

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3000';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3000,88,1,'查看','6666-1000-0','流量套餐订购','流量订购','6666-1000','/ll_flowOrder.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3001';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3001,88,1,'查看','6666-1100-0','流量套餐同步','流量订购','6666-1100','/ll_flowSynchronize.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3002';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3002,89,1,'查看','6666-1200-0','套餐订购详情','数据查询','6666-1200','/ll_orderDetails.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3003';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3003,89,1,'查看','6666-1300-0','套餐订购任务查询','数据查询','6666-1300','/ll_packageOrderQuest.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3004';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3004,89,1,'查看','6666-1400-0','套餐订购历史查询','数据查询','6666-1400','/ll_orderHistoryQuest.htm');
END IF;
END;
/
DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3005';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3005,89,1,'查看','6666-1500-0','短信提醒下行记录','数据查询','6666-1500','/ll_downRecord.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3006';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3006,89,1,'查看','6666-1600-0','短信提醒任务查询','数据查询','6666-1600','/ll_smsTaskQuest.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3007';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3007,89,1,'查看','6666-1700-0','短信提醒历史查询','数据查询','6666-1700','/ll_smsHistoryQuest.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3008';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3008,90,1,'查看','6666-1800-0','套餐订购统计报表','统计报表','6666-1800','/ll_orderReport.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3009';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3009,90,1,'查看','6666-1900-0','操作员统计报表','统计报表','6666-1900','/ll_operatorReport.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3010';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3010,90,1,'查看','6666-2000-0','机构统计报表','统计报表','6666-2000','/ll_mechanismReport.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3011';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3011,91,1,'查看','6666-2100-0','账号配置','账号管理','6666-2100','/ll_accountManage.htm');
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_PRIVILEGE WHERE PRIVILEGE_ID = '3012';
IF VERSION = 0 THEN
	INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE) VALUES(3012,8,1,'查看','1350-1260-0','流量审核','审批管理','1350-1260','/ll_flowReview.htm');
END IF;
END;
/

UPDATE LF_THIR_MENUCONTROL SET ZH_TW_TITLE = '企業流量',ZH_HK_TITLE = 'Enterprise Data' WHERE PRI_MENU IN (88,89,90,91);
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '流量套餐訂購' ,ZH_HK_MENUNAME = 'Data plan order' , ZH_TW_MODNAME = '流量訂購' , ZH_HK_MODNAME = 'Data ordering'  WHERE PRIVILEGE_ID = 3000;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '流量套餐同步' ,ZH_HK_MENUNAME = 'Synchronization' , ZH_TW_MODNAME = '流量訂購' , ZH_HK_MODNAME = 'Data ordering' WHERE PRIVILEGE_ID = 3001;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購詳情' ,ZH_HK_MENUNAME = 'Detail of order' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3002;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購任務查詢' ,ZH_HK_MENUNAME = 'Order task' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3003;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購歷史查詢' ,ZH_HK_MENUNAME = 'History of order' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3004;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '短信提醒下行記錄' ,ZH_HK_MENUNAME = 'SMS reminder record' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3005;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購統計報表' ,ZH_HK_MENUNAME = ' Data plan statistics' , ZH_TW_MODNAME = '統計報表' , ZH_HK_MODNAME = 'Statistical report' WHERE PRIVILEGE_ID = 3008;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '操作員統計報表' ,ZH_HK_MENUNAME = 'Operator statistics' , ZH_TW_MODNAME = '統計報表' , ZH_HK_MODNAME = 'Statistical report' WHERE PRIVILEGE_ID = 3009;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '機構統計報表' ,ZH_HK_MENUNAME = 'Organization statistics' , ZH_TW_MODNAME = '統計報表' , ZH_HK_MODNAME = 'Statistical report' WHERE PRIVILEGE_ID = 3010;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '賬號配置' ,ZH_HK_MENUNAME = 'Settings ' , ZH_TW_MODNAME = '賬號管理' , ZH_HK_MODNAME = 'Account' WHERE PRIVILEGE_ID = 3011;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '流量審核' ,ZH_HK_MENUNAME = 'Data Audit' , ZH_TW_MODNAME = '審批管理' , ZH_HK_MODNAME = 'Approval' WHERE PRIVILEGE_ID = 3012;
COMMIT;


DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3000';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3000);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3000);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3000);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3001';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3001);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3001);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3001);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3002';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3002);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3002);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3002);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3003';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3003);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3003);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3003);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3004';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3004);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3004);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3004);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3005';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3005);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3005);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3005);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3006';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3006);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3006);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3006);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3007';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3007);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3007);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3007);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3008';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3008);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3008);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3008);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3009';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3009);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3009);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3009);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3010';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3010);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3010);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3010);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3011';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3011);   
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3011);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3011);
END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_IMPOWER WHERE PRIVILEGE_ID = '3012';
IF VERSION = 0 THEN
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(1,3012);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(2,3012);
	INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) VALUES(4,3012);
END IF;
END;
/
COMMIT;
---添加字段
------------------------------------------------------
DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_DETAIL') AND COLUMN_NAME = UPPER('REPORTDATE');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_DETAIL ADD  REPORTDATE VARCHAR2(16) DEFAULT '' '' NOT NULL';
    END IF;
END;
/
    
DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_DETAIL2017') AND COLUMN_NAME = UPPER('REPORTDATE');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_DETAIL2017 ADD  REPORTDATE VARCHAR2(16) DEFAULT '' '' NOT NULL';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_DETAIL2018') AND COLUMN_NAME = UPPER('REPORTDATE');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_DETAIL2018 ADD  REPORTDATE VARCHAR2(16) DEFAULT '' '' NOT NULL';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_TASK') AND COLUMN_NAME = UPPER('REPORTDATE');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_TASK ADD  REPORTDATE VARCHAR2(16) DEFAULT '' '' NOT NULL';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_TASK') AND COLUMN_NAME = UPPER('P_IDS');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_TASK ADD  P_IDS VARCHAR2(64) DEFAULT '' '' NOT NULL';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_TASK') AND COLUMN_NAME = UPPER('SERVERNUM');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_TASK ADD  SERVERNUM VARCHAR2(32) DEFAULT ''0'' NOT NULL';
    END IF;
END;
/

----修改字段长度
---------------------------
DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_COMP_INFO') AND COLUMN_NAME = UPPER('LLACCOUNT');
    IF NUM > 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_COMP_INFO MODIFY  LLACCOUNT VARCHAR2(64)';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_COMP_INFO') AND COLUMN_NAME = UPPER('PUSHADDR');
    IF NUM > 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_COMP_INFO MODIFY  PUSHADDR VARCHAR2(128)';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_TASK') AND COLUMN_NAME = UPPER('SMSSTATUS');
    IF NUM > 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_TASK MODIFY  SMSSTATUS VARCHAR2(2)';
    END IF;
END;
/

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('ll_order_task') AND COLUMN_NAME = UPPER('ORDERSTATUS');
    IF NUM > 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE ll_order_task MODIFY  ORDERSTATUS VARCHAR2(2)';
    END IF;
END;
/

---修改字段长度
------------------------------------------------------
DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('ll_product') AND COLUMN_NAME = UPPER('PRODUCTNAME');
    IF NUM > 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE ll_product MODIFY  PRODUCTNAME VARCHAR2(128)';
    END IF;
END;
/

DECLARE
	VERSION INT;
BEGIN
	SELECT COUNT(*) INTO VERSION FROM LF_REVIEWSWITCH WHERE ID = 8;
IF VERSION = 0 THEN
	Insert into LF_REVIEWSWITCH(ID,Switch_Type,Msg_Count,Info_Type,Corp_Code) values(8,1,2,7,100001);
END IF;
END;
/
COMMIT;

DECLARE NUM NUMBER;
BEGIN 
    SELECT COUNT(1) INTO NUM FROM COLS WHERE TABLE_NAME = UPPER('LL_ORDER_TASK') AND COLUMN_NAME = UPPER('MSG');
    IF NUM = 0 THEN 
       EXECUTE IMMEDIATE 'ALTER TABLE LL_ORDER_TASK ADD  MSG VARCHAR2(2048) DEFAULT '' '' NOT NULL';
    END IF;
END;
/

create or replace procedure CREATE_LL_ORDER_DETAIL
is  
  tableName varchar2(64);
    v_createsql varchar2(10000);  
    v_count number(9);  
    v_time varchar2(10); 
begin  
  select extract(year from sysdate)+1 into v_time from dual;
  tableName :='LL_ORDER_DETAIL' || v_time;
    v_createsql:='create table '||tableName||'(  
                    ID  NUMBER(11) NOT NULL,
          MOBILE VARCHAR2(16) DEFAULT '' '' NOT NULL,
          MSG VARCHAR2(2048) DEFAULT '' '' NOT NULL,
          BATCHID NUMBER(11) DEFAULT 0 NOT NULL,
          ORDERNO VARCHAR2(64) DEFAULT '' '' NOT NULL,
          LLRPT VARCHAR2(32) DEFAULT '' '' NOT NULL,
          ERRCODE VARCHAR2(20) DEFAULT '' '' NOT NULL,
          USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
          ORG_ID  NUMBER(11) DEFAULT 0 NOT NULL,
          PRO_ID NUMBER(11) DEFAULT 0 NOT NULL,
          PRODUCTID VARCHAR2(32) DEFAULT '' '' NOT NULL,
          ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          RPTTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          STATUS  NUMBER(11) DEFAULT 0 NOT NULL)';  
    select count(*) into v_count from user_tables where table_name=upper(tableName);  
    if v_count<=0 then  
    EXECUTE IMMEDIATE v_createsql;  
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_MOBILE'|| v_time ||' ON '||tableName||' (MOBILE)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERNO'|| v_time ||' ON '||tableName||' (ORDERNO)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_USER_ID'|| v_time ||' ON '||tableName||' (USER_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORG_ID'|| v_time ||' ON '||tableName||' (ORG_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_PRO_ID'|| v_time ||' ON '||tableName||' (PRO_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERTM'|| v_time ||' ON '||tableName||' (ORDERTM)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_LLPRT'|| v_time ||' ON '||tableName||' (LLRPT)';
    EXECUTE IMMEDIATE 'ALTER TABLE '||tableName||' ADD PRIMARY KEY (ID)';
      commit;  
    end if;   
end;  

DECLARE NUMB NUMBER(10);
BEGIN
SELECT COUNT(1) INTO NUMB FROM USER_JOBS WHERE JOB = 9995;
IF NUMB = 0 THEN
    dbms_job.isubmit(9995,'CREATE_LL_ORDER_DETAIL;',to_date('20180301 10:47:00','yyyyMMdd hh24:mi:ss'),'ADD_MONTHS(trunc(sysdate,''yyyy''),11)+1/24',false);  
END IF;
END;
/

create or replace procedure CREATE_LL_ORDER_DETAIL
is  
    tableName varchar2(64);
    v_createsql varchar2(10000);  
    v_count number(9);  
    v_time varchar2(10); 
begin  
  select extract(year from sysdate)+1 into v_time from dual;
  tableName :='LL_ORDER_DETAIL' || v_time;
    v_createsql:='create table '||tableName||'(  
                    ID  NUMBER(11) NOT NULL,
          MOBILE VARCHAR2(16) DEFAULT '' '' NOT NULL,
          MSG VARCHAR2(2048) DEFAULT '' '' NOT NULL,
          BATCHID NUMBER(11) DEFAULT 0 NOT NULL,
          ORDERNO VARCHAR2(64) DEFAULT '' '' NOT NULL,
          LLRPT VARCHAR2(32) DEFAULT '' '' NOT NULL,
          ERRCODE VARCHAR2(20) DEFAULT '' '' NOT NULL,
          USER_ID NUMBER(11) DEFAULT 0 NOT NULL,
          ORG_ID  NUMBER(11) DEFAULT 0 NOT NULL,
          PRO_ID NUMBER(11) DEFAULT 0 NOT NULL,
          PRODUCTID VARCHAR2(32) DEFAULT '' '' NOT NULL,
          ORDERTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          RPTTM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          UPDATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          CREATETM TIMESTAMP DEFAULT SYSDATE NOT NULL,
          STATUS  NUMBER(11) DEFAULT 0 NOT NULL)';  
    select count(*) into v_count from user_tables where table_name=upper(tableName);  
    if v_count<=0 then  
    EXECUTE IMMEDIATE v_createsql;  
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_MOBILE'|| v_time ||' ON '||tableName||' (MOBILE)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERNO'|| v_time ||' ON '||tableName||' (ORDERNO)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_USER_ID'|| v_time ||' ON '||tableName||' (USER_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORG_ID'|| v_time ||' ON '||tableName||' (ORG_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_PRO_ID'|| v_time ||' ON '||tableName||' (PRO_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_ORDERTM'|| v_time ||' ON '||tableName||' (ORDERTM)';
    EXECUTE IMMEDIATE 'CREATE INDEX INDEX_DETALL_LLPRT'|| v_time ||' ON '||tableName||' (LLRPT)';
    EXECUTE IMMEDIATE 'ALTER TABLE '||tableName||' ADD PRIMARY KEY (ID)';
      commit;  
    end if;   
end;  

declare job_count number(9);
begin 
select count(*) into job_count from user_jobs where job=9999;  
    if job_count<=0 then     
    dbms_job.isubmit(9999,'CREATE_LL_ORDER_DETAIL;',to_date('20180301 10:47:00','yyyyMMdd hh24:mi:ss'),'ADD_MONTHS(trunc(sysdate,''yyyy''),11)+1/24',false); 
    commit;  
    end if;
end;

--增加版本信息
DECLARE COUNTNUM INT;
        DBVERSIONSTR VARCHAR2(32);
        NUMNO INT;
        TOTALINT INT;
BEGIN
    DBVERSIONSTR:='6.39';
    NUMNO:=3;
    TOTALINT:=4;
    SELECT  COUNT(*) INTO COUNTNUM FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR AND CURRENT_NO=NUMNO AND TOTAL=TOTALINT;
    IF COUNTNUM=0 THEN
      --EMP产品数据库版本信息表
      INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
      VALUES(DBVERSIONSTR,SYSDATE,SYSDATE,NUMNO,TOTALINT,2,'3号脚本');
    ELSE
      UPDATE LF_DB_SCRIPT SET STATE=2,UPDATETIME=SYSDATE WHERE  VERSION=DBVERSIONSTR AND CURRENT_NO=NUMNO AND TOTAL=TOTALINT;
    END IF;
    COMMIT;
END;
/

--增加版本信息
DECLARE COUNTNUM INT;
        VERSIONSTR VARCHAR2(32);
        DBVERSIONSTR VARCHAR2(32);
        WBSVERSIONSTR VARCHAR2(32);
        SPGATEVERSIONSTR VARCHAR2(32);
        NUMNO INT;
        TOTALINT INT;
BEGIN
    VERSIONSTR:='7.0.0.395';
    DBVERSIONSTR:='7.00';
    WBSVERSIONSTR:='8.4.10.163';
    SPGATEVERSIONSTR:='6.1.23.316';
  NUMNO:=1;
  TOTALINT:=1;
  --EMP产品版本记录
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
  IF COUNTNUM=0 THEN
   --EMP-WEB
   INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
   VALUES(1000,1000,VERSIONSTR,SYSDATE,SYSDATE,'EMP-WEB');
  ELSE
    UPDATE LF_VERSION SET UPDATETIME=SYSDATE,VERSION=VERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
  END IF;
  COMMIT;
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000;
  IF COUNTNUM=0 THEN
   --EMP_GATEWARY
   INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
   VALUES(1000,2000,WBSVERSIONSTR,SYSDATE,SYSDATE,'EMP_GATEWARY');
  ELSE
    UPDATE LF_VERSION SET UPDATETIME=SYSDATE,VERSION=WBSVERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000;
  END IF;
  COMMIT;
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000;
  IF COUNTNUM=0 THEN
   --SMT_SPGATE
   INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
   VALUES(1000,3000,SPGATEVERSIONSTR,SYSDATE,SYSDATE,'SMT_SPGATE');
  ELSE
    UPDATE LF_VERSION SET UPDATETIME=SYSDATE,VERSION=SPGATEVERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000;
  END IF;
  COMMIT;
  
  --EMP产品版本历史记录
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
  IF COUNTNUM=0 THEN
    --EMP-WEB
    INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO,ISRELEASE,VERSIONINFO)
    VALUES(1000,1000,VERSIONSTR,SYSDATE,SYSDATE,'EMP-WEB',1,'1.新增企业流量');
  ELSE
    UPDATE LF_VERSION_HIS SET UPDATETIME=SYSDATE,ISRELEASE=1,VERSIONINFO='1.新增企业流量' WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000;
  END IF;
  COMMIT; 
  
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=WBSVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
  IF COUNTNUM=0 THEN
    --EMP_GATEWARY
    INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
    VALUES(1000,2000,WBSVERSIONSTR,SYSDATE,SYSDATE,'EMP_GATEWARY');
  ELSE
    UPDATE LF_VERSION_HIS SET UPDATETIME=SYSDATE WHERE VERSION=WBSVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=2000;
  END IF;
  COMMIT; 
  
  SELECT COUNT(*) INTO COUNTNUM FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
  IF COUNTNUM=0 THEN
    --SMT_SPGATE
    INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
    VALUES(1000,3000,SPGATEVERSIONSTR,SYSDATE,SYSDATE,'SMT_SPGATE');
  ELSE
    UPDATE LF_VERSION_HIS SET UPDATETIME=SYSDATE WHERE VERSION=SPGATEVERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=3000;
  END IF;
  COMMIT; 

  SELECT COUNT(*) INTO COUNTNUM FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR;
  IF COUNTNUM=0 THEN
    --EMP产品数据库版本信息表
    INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
    VALUES(DBVERSIONSTR,SYSDATE,SYSDATE,NUMNO,TOTALINT,2,'网关包更改');
  ELSE
    UPDATE LF_DB_SCRIPT SET STATE=2,UPDATETIME=SYSDATE WHERE  VERSION=DBVERSIONSTR AND CURRENT_NO=NUMNO AND TOTAL=TOTALINT;
  END IF;
  COMMIT;
END; 
/
--重新编译所有存储过程和触发器   
CALL COMPILE_PROCEDURE();
/
-----------V6.35-V6.39 END------------------------   


    