/*****V71.01-V71.02 START*/
DROP PROCEDURE IF EXISTS `LF_PVERV0`;
DELIMITER ;;
CREATE DEFINER=`root`@`%`  PROCEDURE `LF_PVERV0`(
    DBVERSIONSTR VARCHAR(32),
    NUM INT,
    TOTALSTR INT
)
BEGIN
    IF NOT EXISTS(SELECT * FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR) THEN
    /*EMP产品数据库版本信息表*/
    INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
    VALUES(DBVERSIONSTR,NOW(),NOW(),NUM,TOTALSTR,1,'Web脚本更新');
    END IF;
END
;; DELIMITER ;
CALL LF_PVERV0('71.01',1,1);
DROP PROCEDURE IF EXISTS `LF_PVERV0`;

/* 网关升级脚本START */
/* 网关升级脚本END */

/*EMP升级脚本    START*/
/*企业富信-批量导入模板发送*/
INSERT INTO lf_privilege (PRIVILEGE_ID, RESOURCE_ID, OPERATE_ID, COMMENTS, PRIV_CODE, MENUNAME, MODNAME, MENUCODE, MENUSITE, ZH_TW_COMMENTS, ZH_HK_COMMENTS, ZH_TW_MENUNAME, ZH_HK_MENUNAME, ZH_TW_MODNAME, ZH_HK_MODNAME)
SELECT '3553', '95', '1', '查看', '5100-1850-0', '批量导入模板发送', '数据查询', '5100-1850', '/importTemplateDetails.htm', '查看', 'View', '批量導入模板發送', 'Import Temp And Send', '數據查詢', 'Data query' FROM DUAL
WHERE NOT EXISTS(SELECT * FROM LF_PRIVILEGE WHERE PRIVILEGE_ID=3553);


INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3553 FROM DUAL WHERE NOT EXISTS(SELECT * FROM LF_IMPOWER WHERE PRIVILEGE_ID=3553 AND ROLE_ID=2);




-- 创建模板导入批次表

CREATE TABLE IF NOT EXISTS `LF_TEMP_IMPORT_BATCH`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`BATCH` INT(11) NOT NULL DEFAULT 0,
  `CORP_CODE` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`CORP_NAME` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`AMOUNT` BIGINT(20) NOT NULL DEFAULT 0,
	`SUCCESS_AMOUNT` BIGINT(20) NOT NULL DEFAULT 0,
	`FAIL_AMOUNT` BIGINT(20) NOT NULL DEFAULT 0,
	`PROCESS_STATUS` INT(11) NOT NULL DEFAULT 0,
	`TM_NAME` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`ADDTIME` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=GBK;

-- 创建导入详情表
CREATE TABLE IF NOT EXISTS `LF_TEMP_IMPORT_DETAILS`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`BATCH` INT(11) NOT NULL DEFAULT 0,
  `TM_NAME` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`NAME` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`PHONE_NUM` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`SCORE` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`SPTEMPLID` BIGINT(20),
	`SEND_STATUS` INT(11) NOT NULL DEFAULT 0,
	`IMPORT_STATUS` INT(11) NOT NULL DEFAULT 0,
	`CAUSE` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`IMAGE_SRC` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`VIDEO_SRC` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`CORP_CODE` VARCHAR(64) CHARACTER SET GBK COLLATE GBK_CHINESE_CI NULL DEFAULT '',
	`ADDTIME` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=GBK;

-- LF_TEMPLATE 添加SOURCE 字段[富信模板来源]
DROP PROCEDURE IF EXISTS ADDCOL;
CREATE PROCEDURE ADDCOL()
BEGIN
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND COLUMN_NAME='SOURCE' AND TABLE_NAME='LF_TEMPLATE') THEN
	ALTER TABLE LF_TEMPLATE ADD COLUMN `SOURCE` INT NOT NULL DEFAULT 1 ;
END IF;
END;
CALL ADDCOL();
DROP PROCEDURE ADDCOL;

DELIMITER;
DROP PROCEDURE IF EXISTS SCHEMA_CHANGE;
CREATE PROCEDURE SCHEMA_CHANGE()
BEGIN
/**
   *（LF_SUB_TEMPLATE）
   *修改 ENDJSON 长度
**/
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE()  AND TABLE_NAME = 'LF_SUB_TEMPLATE' AND COLUMN_NAME = 'ENDJSON') THEN
        ALTER TABLE LF_SUB_TEMPLATE MODIFY COLUMN ENDJSON BLOB  NOT NULL;
	END IF;
END;
DELIMITER ;
CALL SCHEMA_CHANGE();
DROP PROCEDURE IF EXISTS SCHEMA_CHANGE;

-- LF_SUB_TEMPLATE 添加H5TYPE 字段[H5长页短页]
DROP PROCEDURE IF EXISTS ADDCOL;
CREATE PROCEDURE ADDCOL()
BEGIN
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND COLUMN_NAME='H5TYPE' AND TABLE_NAME='LF_SUB_TEMPLATE') THEN
	ALTER TABLE LF_SUB_TEMPLATE ADD COLUMN `H5TYPE` INT NOT NULL DEFAULT 0 ;
END IF;
END;
CALL ADDCOL();
DROP PROCEDURE IF EXISTS ADDCOL;

-- LF_SUB_TEMPLATE 添加APP字段[H5封面JSON]
DROP PROCEDURE IF EXISTS ADDCOL;
CREATE PROCEDURE ADDCOL()
BEGIN
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND COLUMN_NAME='APP' AND TABLE_NAME='LF_SUB_TEMPLATE') THEN
	ALTER TABLE LF_SUB_TEMPLATE ADD COLUMN `APP` BLOB NOT NULL;
END IF;
END;
CALL ADDCOL();
DROP PROCEDURE IF EXISTS ADDCOL;

-- LF_SUB_TEMPLATE 添加H5URL字段[H5生成的HTML服务器地址]
DROP PROCEDURE IF EXISTS ADDCOL;
CREATE PROCEDURE ADDCOL()
BEGIN
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND COLUMN_NAME='H5URL' AND TABLE_NAME='LF_SUB_TEMPLATE') THEN
	ALTER TABLE LF_SUB_TEMPLATE ADD COLUMN `H5URL` VARCHAR(255) NOT NULL DEFAULT ' ';
END IF;
END;
CALL ADDCOL();
DROP PROCEDURE IF EXISTS ADDCOL;

-- 创建素材表
CREATE TABLE IF NOT EXISTS LF_FODDER(
    ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT DEFAULT 0 NOT NULL,
    URL VARCHAR(200) DEFAULT ' ' NOT NULL,
    FO_TYPE INT DEFAULT 0 NOT NULL,
    FO_SIZE INT DEFAULT 0 NOT NULL,
    WIDTH INT DEFAULT 0 NOT NULL,
    HEIGHT INT DEFAULT 0 NOT NULL,
    DURATION INT DEFAULT 0 NOT NULL,
    FO_STATUS INT DEFAULT 0 NOT NULL,
    RADIO VARCHAR(50) DEFAULT ' ' NOT NULL,
    ORIGINAL VARCHAR(200) DEFAULT ' ' NOT NULL
);

-- LF_FODDER 添加FIRSTFRAMEPATH字段
DROP PROCEDURE IF EXISTS  ADDCOL;
CREATE PROCEDURE ADDCOL()
BEGIN
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND COLUMN_NAME='FIRSTFRAMEPATH' AND TABLE_NAME='LF_FODDER') THEN
	ALTER TABLE LF_FODDER ADD COLUMN `FIRSTFRAMEPATH` VARCHAR(64) NOT NULL DEFAULT '';
END IF;
END;
CALL ADDCOL();
DROP PROCEDURE ADDCOL;

DELIMITER;
DROP PROCEDURE IF EXISTS SCHEMA_CHANGE;
CREATE PROCEDURE SCHEMA_CHANGE()
BEGIN
/**
   *模板参数表（LF_TEMP_PARAM)
   *修改 REGCONTENT 长度
**/
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE()  AND TABLE_NAME = 'LF_TEMP_PARAM' AND COLUMN_NAME = 'REGCONTENT') THEN
        ALTER TABLE LF_TEMP_PARAM MODIFY COLUMN REGCONTENT VARCHAR(50) ;
	END IF;
END;
DELIMITER ;
CALL SCHEMA_CHANGE();
DROP PROCEDURE IF EXISTS SCHEMA_CHANGE;


-- 为 MT_DATAREPORT 表添加 RECFAIL字段
DELIMITER ;;
DROP PROCEDURE IF EXISTS `ADDCOL`;
CREATE DEFINER=`root`@`%` PROCEDURE ADDCOL()
BEGIN
IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND COLUMN_NAME='RECFAIL' AND TABLE_NAME='MT_DATAREPORT') THEN
	ALTER TABLE MT_DATAREPORT ADD RECFAIL INT(11) DEFAULT 0 NOT NULL;
END IF;
END;;
 DELIMITER ;
CALL ADDCOL();
DROP PROCEDURE IF EXISTS `ADDCOL`;

-- 档位统计报表转移存储过程（是拿标准版7.1之前改好的直接来用）
DELIMITER ;;
DROP PROCEDURE IF EXISTS `GW_H_STATISTIV3`;
CREATE DEFINER=`root`@`%` PROCEDURE `GW_H_STATISTIV3`(P_PROCESSFLAG INT,ISP1 INT,ISP2 INT,ISP3 INT,ISP4 INT)
BEGIN
	DECLARE P_STR NVARCHAR(4000);
	DECLARE P_USERID VARCHAR(11);
	DECLARE P_TASKID INT;
	DECLARE P_IYMD INT;
	DECLARE P_SPGATE VARCHAR(21);
	DECLARE P_SPISUNCM INT;
	DECLARE P_SVRTYPE VARCHAR(64);
	DECLARE P_SPID VARCHAR(21);
	DECLARE P_P1 VARCHAR(64);
	DECLARE P_P2 VARCHAR(64);
	DECLARE P_P3 VARCHAR(64);
	DECLARE P_P4 VARCHAR(64);
	DECLARE P_IHOUR INT;
	DECLARE P_IYEAR INT ;
	DECLARE P_IMONTH INT;
	DECLARE P_ICOUNT INT;
	DECLARE P_SUCC INT;
	DECLARE P_FAIL INT;
	DECLARE P_NRET INT;
  DECLARE MAXCNT INT ;
  DECLARE I INT;
  DECLARE P_SENDTYPE INT;
  DECLARE P_MOBILEAREA INT;
  DECLARE MINIYMD BIGINT;
  DECLARE MAXIYMD BIGINT;
        DROP TEMPORARY TABLE IF  EXISTS P_TMP_STICV2;
	CREATE TEMPORARY TABLE IF NOT EXISTS P_TMP_STICV2( TMP_ID INT UNSIGNED NOT NULL AUTO_INCREMENT, USERID VARCHAR(11),TASKID INT,SPGATE VARCHAR(21),SPISUNCM INT,
	SPID VARCHAR(32),SVRTYPE VARCHAR(64),P1 VARCHAR(64),P2 VARCHAR(64),P3 VARCHAR(64),P4 VARCHAR(64),
  IYMD INT,IYEAR INT,IMONTH INT,IHOUR INT,ICOUNT INT,SUCC INT,FAIL INT,RECFAIL INT,NRET INT,SENDTYPE INT,MOBILEAREA INT,BATCHID BIGINT,AREACODE INT,TMPLID BIGINT,
  CHGRADE TINYINT,MSGTYPE TINYINT, PRIMARY KEY (TMP_ID)  );
  ALTER TABLE P_TMP_STICV2 AUTO_INCREMENT=1;



	SET P_STR = 'SELECT USERID,TASKID,SPGATE,UNICOM,SPID,SVRTYPE';
        IF  ISP1 =1 THEN
           SET P_STR =CONCAT(P_STR,',P1');
        ELSE
            SET P_STR =CONCAT(P_STR,', '' '' AS P1');
         END IF;
           IF  ISP2 =1 THEN
           SET P_STR =CONCAT(P_STR,',P2');
        ELSE
            SET P_STR =CONCAT(P_STR,', '' '' AS P2');
         END IF;
    IF  ISP3 =1 THEN
           SET P_STR =CONCAT(P_STR,',P3');
        ELSE
            SET P_STR =CONCAT(P_STR,', '' '' AS P3');
         END IF;
    IF  ISP4 =1 THEN
           SET P_STR =CONCAT(P_STR,',P4');
        ELSE
            SET P_STR =CONCAT(P_STR,', '' '' AS P4');
         END IF;
           SET P_STR =CONCAT(P_STR, ',CAST(DATE_FORMAT(SENDTIME,''%Y%m%d'') AS SIGNED) AS IYMD,
           CAST(DATE_FORMAT(SENDTIME,''%Y'') AS SIGNED) AS IYEAR,
           CAST(DATE_FORMAT(SENDTIME,''%m'') AS SIGNED) AS MON,
           CAST(DATE_FORMAT(SENDTIME,''%H'') AS SIGNED) AS HOUR,
           COUNT(ID),
           SUM(CASE RTRIM(ERRORCODE) WHEN ''DELIVRD'' THEN 1 WHEN ''0'' THEN 1 ELSE 0 END),
           SUM(CASE SUBSTRING(RTRIM(ERRORCODE),1,3) WHEN ''E1:'' THEN 1 WHEN ''E2:'' THEN 1 ELSE 0 END),
					 SUM(CASE SUBSTRING(RTRIM(ERRORCODE),1,3) WHEN ''E2:'' THEN 1 ELSE 0 END),
           SUM(CASE RTRIM(ERRORCODE) WHEN '''' THEN 1 ELSE 0 END),
           SENDTYPE,
           MOBILEAREA,
           BATCHID,AREACODE,TMPLID,CHGRADE,MSGTYPE
           FROM GW_MT_TASK_BAK WHERE  SENDTIME >=  ''') ;
           SET P_STR=CONCAT(P_STR, DATE_SUB(CURDATE(),INTERVAL P_PROCESSFLAG DAY));
           SET P_STR=CONCAT(P_STR,'''  AND SENDTIME < ''');
           SET P_STR=CONCAT(P_STR, CURDATE());
           SET P_STR=CONCAT(P_STR, ''' GROUP BY USERID,TASKID,SPGATE,UNICOM,SPID,SVRTYPE');
            IF  ISP1 =1 THEN
               SET P_STR =CONCAT(P_STR,',P1');
             END IF;
           IF  ISP2 =1 THEN
               SET P_STR =CONCAT(P_STR,',P2');
             END IF;
           IF  ISP3 =1 THEN
               SET P_STR =CONCAT(P_STR,',P3');
           END IF;
           IF  ISP4 =1 THEN
               SET P_STR =CONCAT(P_STR,',P4');
           END IF;
           SET P_STR=CONCAT(P_STR,',SENDTYPE,MOBILEAREA,BATCHID,AREACODE,TMPLID,CHGRADE,MSGTYPE,
           CAST(DATE_FORMAT(SENDTIME,''%Y%m%d'') AS SIGNED),
           CAST(DATE_FORMAT(SENDTIME,''%Y'') AS SIGNED),
           CAST(DATE_FORMAT(SENDTIME,''%m'') AS SIGNED),
           CAST(DATE_FORMAT(SENDTIME,''%H'') AS SIGNED)');

# SELECT P_STR;

  SET @SQL =CONCAT('INSERT INTO P_TMP_STICV2(USERID ,TASKID,SPGATE,SPISUNCM,SPID ,SVRTYPE,P1,P2,P3,P4,IYMD,IYEAR,IMONTH,IHOUR,ICOUNT,SUCC,FAIL,RECFAIL,NRET,SENDTYPE,MOBILEAREA,BATCHID,AREACODE,TMPLID,CHGRADE,MSGTYPE)', P_STR);#
       PREPARE SL FROM @SQL;
       EXECUTE SL;
       DEALLOCATE PREPARE SL;
   SELECT MIN(IYMD),MAX(IYMD) INTO  MINIYMD,MAXIYMD FROM P_TMP_STICV2 ;
  # DELETE FROM MT_DATAREPORT WHERE IYMD BETWEEN   CAST(DATE_FORMAT(DATE_SUB(CURDATE(),INTERVAL P_PROCESSFLAG DAY),'%Y%m%d') AS SIGNED ) AND  CAST(DATE_FORMAT(CURDATE(),'%Y%m%d') AS SIGNED );

  DELETE FROM MT_DATAREPORT WHERE IYMD BETWEEN   MINIYMD AND  MAXIYMD;
	INSERT INTO MT_DATAREPORT (USERID,TASKID,SPGATE,SPISUNCM,SPID,SVRTYPE,P1,P2,P3,P4,IYMD,IHOUR,IMONTH,Y,ICOUNT,RSUCC,RFAIL1,RFAIL2,RECFAIL,RNRET,SENDTYPE,MOBILEAREA,BATCHID,AREACODE,TMPLID,CHGRADE,MSGTYPE)
	SELECT T.USERID,T.TASKID,T.SPGATE,T.SPISUNCM,T.SPID,T.SVRTYPE,T.P1,T.P2,T.P3,T.P4,T.IYMD,T.IHOUR,T.IMONTH,T.IYEAR,T.ICOUNT,T.SUCC,T.FAIL,(T.ICOUNT-T.SUCC-T.FAIL-T.NRET),T.RECFAIL,T.NRET,T.SENDTYPE,T.MOBILEAREA,T.BATCHID,T.AREACODE,T.TMPLID,T.CHGRADE,T.MSGTYPE FROM P_TMP_STICV2 T;

  TRUNCATE TABLE P_TMP_STICV2;
END;;
DELIMITER ;


/*EMP升级脚本    END*/

DROP PROCEDURE IF EXISTS `LF_PVERV0`;
DELIMITER ;;
CREATE DEFINER=`root`@`%` PROCEDURE `LF_PVERV0`(
    VERSIONSTR VARCHAR(32),
    DBVERSIONSTR VARCHAR(32),
    WBSVERSION VARCHAR(32),
    SPGATEVERSION VARCHAR(32),
    NUM INT,
    TOTALSTR INT
)
BEGIN
	/*EMP产品版本记录*/
	/*EMP-WEB*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,1000,VERSIONSTR,NOW(),NOW(),'EMP-WEB');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=VERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
	END IF;
	/*EMP_GATEWAY*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,2000,WBSVERSION,NOW(),NOW(),'EMP_GATEWAY');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=WBSVERSION WHERE  PRODUCT_ID=1000 AND PROCESS_ID=2000;
	END IF;
	/*SMT_SPGATE*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,3000,SPGATEVERSION,NOW(),NOW(),'SMT_SPGATE');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=SPGATEVERSION WHERE  PRODUCT_ID=1000 AND PROCESS_ID=3000;
	END IF;
	/*EMP产品版本历史记录*/
	/*EMP-WEB*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
			INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO,ISRELEASE,VERSIONINFO)
			VALUES(1000,1000,VERSIONSTR,NOW(),NOW(),'EMP-WEB',1,'1.新增企业流量');
	ELSE
			UPDATE LF_VERSION_HIS SET UPDATETIME=NOW(),ISRELEASE=1,VERSIONINFO='1.新增企业流量' WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
	END IF;
	/*EMP_GATEWAY*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION AND PRODUCT_ID=1000 AND PROCESS_ID=2000) THEN
		INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,2000,WBSVERSION,NOW(),NOW(),'EMP_GATEWAY');
	ELSE
		UPDATE LF_VERSION_HIS SET UPDATETIME=NOW() WHERE  PRODUCT_ID=1000 AND PROCESS_ID=2000;
	END IF;
	/*SMT_SPGATE*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION AND PRODUCT_ID=1000 AND PROCESS_ID=3000) THEN
		INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,3000,SPGATEVERSION,NOW(),NOW(),'SMT_SPGATE');
	ELSE
		UPDATE LF_VERSION_HIS SET UPDATETIME=NOW() WHERE  PRODUCT_ID=1000 AND PROCESS_ID=3000;
	END IF;
	IF NOT EXISTS(SELECT * FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR AND CURRENT_NO=NUM AND TOTAL=TOTALSTR) THEN
		/*EMP产品数据库版本信息表*/
		INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
		VALUES(DBVERSIONSTR,NOW(),NOW(),NUM,TOTALSTR,2,'1号脚本');
	ELSE
		UPDATE LF_DB_SCRIPT SET STATE=2,UPDATETIME=NOW() WHERE  CURRENT_NO=NUM AND TOTAL=TOTALSTR;
	END IF;
END
;; DELIMITER ;
CALL LF_PVERV0('7.1.1.423.SP1','71.01','8.5.13.211','6.1.46.338',3,3);
DROP PROCEDURE IF EXISTS `LF_PVERV0`;
/*****V71.00-V71.01 END*/