
BEGIN
    IF NOT EXISTS (SELECT BPNAME FROM SYSCAT.BUFFERPOOLS WHERE BPNAME='MWSMSBP') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE ' 
CREATE BUFFERPOOL "MWSMSBP"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE 1024
  AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 16K   
  ';
      END;
    END IF;
COMMIT;
END &&
  
--创建数据表空间
BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='EMP_TABLESPACE') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE ' 
CREATE LARGE TABLESPACE "EMP_TABLESPACE"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 256
  PREFETCHSIZE 192
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 15G
  DROPPED TABLE RECOVERY OFF
  ';
      END;
    END IF;
COMMIT;
END &&
  
  BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TBSPHISTORY') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE ' 
CREATE LARGE TABLESPACE "TBSPHISTORY"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 512M
  DROPPED TABLE RECOVERY OFF
  ';
      END;
    END IF;
COMMIT;
END &&

 BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TBSPHISINDEX') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE LARGE TABLESPACE "TBSPHISINDEX"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 512M
  DROPPED TABLE RECOVERY OFF
   ';
      END;
    END IF;
COMMIT;
END &&

BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TBSPMTTASKDATA') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE LARGE TABLESPACE "TBSPMTTASKDATA"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY ON
';
      END;
    END IF;
COMMIT;
END &&

BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TBSPMTTASKINDEX') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE LARGE TABLESPACE "TBSPMTTASKINDEX"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY ON
';
      END;
    END IF;
COMMIT;
END &&

BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TBSPSVRDATA') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE LARGE TABLESPACE "TBSPSVRDATA"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY OFF
';
      END;
    END IF;
COMMIT;
END &&

BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TBSPSVRINDEX') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE LARGE TABLESPACE "TBSPSVRINDEX"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY ON
';
      END;
    END IF;
COMMIT;
END &&

BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='TPACCMGR') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE LARGE TABLESPACE "TPACCMGR"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 128M
  DROPPED TABLE RECOVERY OFF
';
      END;
    END IF;
COMMIT;
END &&

BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='USERTEMPSPACE') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE USER TEMPORARY TABLESPACE "USERTEMPSPACE"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE AUTOMATIC
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  DROPPED TABLE RECOVERY OFF
';
      END;
    END IF;
COMMIT;
END &&

  

--增加一个系统缓冲池
BEGIN
    IF NOT EXISTS (SELECT TBSPACE FROM SYSCAT.TABLESPACES WHERE TBSPACE='MWSYSTEMPSPACE1') THEN
	  BEGIN ATOMIC
            EXECUTE IMMEDIATE '
CREATE  SYSTEM TEMPORARY  TABLESPACE MWSYSTEMPSPACE1
PAGESIZE 16K
MANAGED BY AUTOMATIC STORAGE
EXTENTSIZE 16
OVERHEAD 10.5
PREFETCHSIZE 16
TRANSFERRATE 0.14
BUFFERPOOL  "MWSMSBP"
';
      END;
    END IF;
COMMIT;
END &&