CREATE BUFFERPOOL "MWSMSBP"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE 1024
  AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 16K;
  CREATE LARGE TABLESPACE "EMP_TABLESPACE"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 256
  PREFETCHSIZE 192
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 15G
  DROPPED TABLE RECOVERY OFF;

CREATE LARGE TABLESPACE "TBSPHISTORY"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 512M
  DROPPED TABLE RECOVERY OFF;
  
CREATE LARGE TABLESPACE "TBSPHISINDEX"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 512M
  DROPPED TABLE RECOVERY OFF;

CREATE LARGE TABLESPACE "TBSPMTTASKDATA"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE "TBSPMTTASKINDEX"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE "TBSPSVRDATA"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY OFF;

CREATE LARGE TABLESPACE "TBSPSVRINDEX"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 1G
  DROPPED TABLE RECOVERY ON;

CREATE LARGE TABLESPACE "TPACCMGR"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  AUTORESIZE YES INCREASESIZE 128M
  DROPPED TABLE RECOVERY OFF;

CREATE USER TEMPORARY TABLESPACE "USERTEMPSPACE"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  EXTENTSIZE 32
  PREFETCHSIZE AUTOMATIC
  BUFFERPOOL "MWSMSBP"
  OVERHEAD 12.67
  TRANSFERRATE 0.18
  DROPPED TABLE RECOVERY OFF;
  
--增加一个系统缓冲池  
CREATE  SYSTEM TEMPORARY  TABLESPACE MWSYSTEMPSPACE1 
PAGESIZE 16 K  
MANAGED BY AUTOMATIC STORAGE 
EXTENTSIZE 16 
OVERHEAD 10.5 
PREFETCHSIZE 16 
TRANSFERRATE 0.14 
BUFFERPOOL  MWSMSBP ;
COMMENT ON TABLESPACE MWSYSTEMPSPACE1 IS '系统临时';



