
/**创建存储过程，用于判断索引是否存在，存在则删除该索引**/
DROP PROCEDURE IF EXISTS DEL_INX;
CREATE PROCEDURE DEL_INX(IN P_TABLENAE varchar(200), IN P_IDXNAME VARCHAR(200))
BEGIN 
	DECLARE STR VARCHAR(250);
	DECLARE TB_SCHEMA VARCHAR(36);
	SET @STR = CONCAT(' DROP INDEX  ', P_IDXNAME, ' ON ', P_TABLENAE);
	SELECT DATABASE() INTO @TB_SCHEMA;
  SELECT COUNT(1) INTO @CNT FROM information_schema.STATISTICS WHERE TABLE_SCHEMA = @TB_SCHEMA and TABLE_NAME =  P_TABLENAE AND INDEX_NAME = P_IDXNAME;
  IF @CNT > 0 THEN
		PREPARE STMT FROM @STR;
		EXECUTE STMT;
	END IF;
END;         

/**创建表**/
CREATE TABLE IF NOT EXISTS LL_ORDER_TASK(
			ID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      TASKID BIGINT(36) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR(36) DEFAULT '' NOT NULL,
      ECID VARCHAR(16) DEFAULT '' NOT NULL,
      USER_ID int(11) DEFAULT 0 NOT NULL,
      ORG_ID int(11) DEFAULT 0 NOT NULL,
      TOPIC VARCHAR(64) DEFAULT '' NOT NULL,
      PRO_IDS VARCHAR(32) DEFAULT '' NOT NULL,
      MSGTYPE CHAR(1) DEFAULT '1' NOT NULL,
      TEMP_ID INT(11) DEFAULT 0 NOT NULL,
      SP_USER VARCHAR(32) DEFAULT '' NOT NULL,
      SP_PWD VARCHAR(32) DEFAULT '' NOT NULL,
      SUBCOUNT int(11) DEFAULT 0 NOT NULL,
      EFFCOUNT int(11) DEFAULT 0 NOT NULL,
      SUCCOUNT INT(11) DEFAULT 0 NOT NULL,
      FAICOUNT INT(11) DEFAULT 0 NOT NULL,
      TIMER_STATUS CHAR(1) DEFAULT '1' NOT NULL,
      TIMER_TIME TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      RE_STATUS CHAR(1) DEFAULT '1' NOT NULL,
      ORDERSTATUS VARCHAR(2) DEFAULT '-1' NOT NULL,
      SMSSTATUS VARCHAR(2) DEFAULT '-1' NOT NULL,
      ISRETRY CHAR(1) DEFAULT '1' NOT NULL,
      SUBMITTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      UPDATETM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      SUMMONEY DOUBLE(12,2) DEFAULT 0 NOT NULL,
	  REPORTDATE VARCHAR(16) DEFAULT '' NOT NULL,
	  MSG VARCHAR(2048) DEFAULT '' NOT NULL,
	  P_IDS VARCHAR(64) DEFAULT '' NOT NULL,
	  SERVERNUM VARCHAR(32) DEFAULT '0' NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CALL DEL_INX('ll_order_task','INDEX_TASK_USER_ID');
ALTER TABLE LL_ORDER_TASK ADD INDEX INDEX_TASK_USER_ID(USER_ID);
CALL DEL_INX('ll_order_task','INDEX_TASK_ORDERTM');
ALTER TABLE LL_ORDER_TASK ADD INDEX INDEX_TASK_ORDERTM(REPORTDATE);
CALL DEL_INX('ll_order_task','INDEX_TASK_ORG_ID');
ALTER TABLE LL_ORDER_TASK ADD INDEX INDEX_TASK_ORG_ID(ORG_ID);



CREATE TABLE IF NOT EXISTS LL_PRODUCT(
	  ID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      ECID INT(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR(32) DEFAULT '' NOT NULL,
      PRODUCTNAME VARCHAR(128) DEFAULT '' NOT NULL,
      ISP VARCHAR(16) DEFAULT '' NOT NULL,
      VOLUME VARCHAR(16) DEFAULT '' NOT NULL,
      PRICE DOUBLE(11,2) DEFAULT 0 NOT NULL,
      DISCPRICE DOUBLE(11,2)  DEFAULT 0 NOT NULL,
      AREA VARCHAR(32) DEFAULT '' NOT NULL,
      PTYPE INT(11) DEFAULT 0 NOT NULL,
      PMOLD INT(11) DEFAULT 0 NOT NULL,
      RTYPE INT(11) DEFAULT 0 NOT NULL,
      STATUS INT(11) DEFAULT 0 NOT NULL,
      UPDATETM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      OPERATORID INT(11) DEFAULT 0 NOT NULL    
)ENGINE=INNODB DEFAULT CHARSET=UTF8;

CALL DEL_INX('ll_product','INDEX_PRO_PRODUCTID');
ALTER TABLE LL_PRODUCT ADD INDEX INDEX_PRO_PRODUCTID(PRODUCTID);
CALL DEL_INX('ll_product','INDEX_PRO_PRODUCTNAME');
ALTER TABLE LL_PRODUCT ADD INDEX INDEX_PRO_PRODUCTNAME(PRODUCTNAME);


CREATE TABLE IF NOT EXISTS LL_COMP_INFO(
			ID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      LLACCOUNT VARCHAR(64) DEFAULT '' NOT NULL,
      PASSWORD VARCHAR(64) DEFAULT '' NOT NULL,
      ECID INT(11) DEFAULT 0 NOT NULL,
      ECNAME VARCHAR(32) DEFAULT '' NOT NULL,
      IP VARCHAR(24) DEFAULT '' NOT NULL,
      PORT INT(11) DEFAULT 0 NOT NULL,
      REMARK VARCHAR(1024) DEFAULT '' NOT NULL,
      UPDATETM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      CREATEID INT(11) DEFAULT 0 NOT NULL,
      UPDATEID INT(11) DEFAULT 0 NOT NULL,
      PUSHADDR VARCHAR(128) DEFAULT '' NOT NULL
)ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE IF NOT EXISTS LL_ORDER_DETAIL(
			ID  INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      MOBILE VARCHAR(16) DEFAULT '' NOT NULL,
      MSG VARCHAR(2048) DEFAULT '' NOT NULL,
      BATCHID INT(11) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR(64) DEFAULT '' NOT NULL,
      LLRPT VARCHAR(32) DEFAULT '' NOT NULL,
			ERRCODE VARCHAR(20) DEFAULT '' NOT NULL,
      USER_ID INT(11) DEFAULT 0 NOT NULL,
      ORG_ID  INT(11) DEFAULT 0 NOT NULL,
      PRO_ID INT(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR(32) DEFAULT '' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      RPTTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      UPDATETM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      STATUS	INT(11) DEFAULT 0 NOT NULL,
			REPORTDATE VARCHAR(16) DEFAULT '' NOT NULL
);

CALL DEL_INX('ll_order_detail','INDEX_DETALL_MOBILE');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_MOBILE(MOBILE);
CALL DEL_INX('ll_order_detail','INDEX_DETALL_ORDERNO');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_ORDERNO(ORDERNO);
CALL DEL_INX('ll_order_detail','INDEX_DETALL_USER_ID');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_USER_ID(USER_ID);
CALL DEL_INX('ll_order_detail','INDEX_DETALL_ORG_ID');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_ORG_ID(ORG_ID);
CALL DEL_INX('ll_order_detail','INDEX_DETALL_PRO_ID');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_PRO_ID(PRO_ID);
CALL DEL_INX('ll_order_detail','INDEX_DETALL_ORDERTM');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_ORDERTM(REPORTDATE);
CALL DEL_INX('ll_order_detail','INDEX_DETALL_LLPRT');
ALTER TABLE LL_ORDER_DETAIL ADD INDEX INDEX_DETALL_LLPRT(LLRPT);


CREATE TABLE IF NOT EXISTS LL_ORDER_DETAIL2017(
	  ID  INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      MOBILE VARCHAR(16) DEFAULT '' NOT NULL,
      MSG VARCHAR(2048) DEFAULT '' NOT NULL,
      BATCHID INT(11) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR(64) DEFAULT '' NOT NULL,
      LLRPT VARCHAR(32) DEFAULT '' NOT NULL,
	  ERRCODE VARCHAR(20) DEFAULT '' NOT NULL,
      USER_ID INT(11) DEFAULT 0 NOT NULL,
      ORG_ID  INT(11) DEFAULT 0 NOT NULL,
      PRO_ID INT(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR(32) DEFAULT '' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      RPTTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      UPDATETM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      STATUS	INT(11) DEFAULT 0 NOT NULL,
	  REPORTDATE VARCHAR(16) DEFAULT '' NOT NULL
);

CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_MOBILE2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_MOBILE2017(MOBILE);
CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_ORDERNO2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_ORDERNO2017(ORDERNO);
CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_USER_ID2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_USER_ID2017(USER_ID);
CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_ORG_ID2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_ORG_ID2017(ORG_ID);
CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_PRO_ID2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_PRO_ID2017(PRO_ID);
CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_ORDERTM2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_ORDERTM2017(REPORTDATE);
CALL DEL_INX('ll_order_detail2017','INDEX_DETALL_LLPRT2017');
ALTER TABLE LL_ORDER_DETAIL2017 ADD INDEX INDEX_DETALL_LLPRT2017(LLRPT);


CREATE TABLE IF NOT EXISTS LL_ORDER_DETAIL2018(
			ID  INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      MOBILE VARCHAR(16) DEFAULT '' NOT NULL,
      MSG VARCHAR(2048) DEFAULT '' NOT NULL,
      BATCHID INT(11) DEFAULT 0 NOT NULL,
      ORDERNO VARCHAR(64) DEFAULT '' NOT NULL,
      LLRPT VARCHAR(32) DEFAULT '' NOT NULL,
	  ERRCODE VARCHAR(20) DEFAULT '' NOT NULL,
      USER_ID INT(11) DEFAULT 0 NOT NULL,
      ORG_ID  INT(11) DEFAULT 0 NOT NULL,
      PRO_ID INT(11) DEFAULT 0 NOT NULL,
      PRODUCTID VARCHAR(32) DEFAULT '' NOT NULL,
      ORDERTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      RPTTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      UPDATETM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
      STATUS	INT(11) DEFAULT 0 NOT NULL,
	  REPORTDATE VARCHAR(16) DEFAULT '' NOT NULL
);

CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_MOBILE2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_MOBILE2018(MOBILE);
CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_ORDERNO2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_ORDERNO2018(ORDERNO);
CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_USER_ID2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_USER_ID2018(USER_ID);
CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_ORG_ID2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_ORG_ID2018(ORG_ID);
CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_PRO_ID2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_PRO_ID2018(PRO_ID);
CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_ORDERTM2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_ORDERTM2018(REPORTDATE);
CALL DEL_INX('ll_order_detail2018','INDEX_DETALL_LLPRT2018');
ALTER TABLE LL_ORDER_DETAIL2018 ADD INDEX INDEX_DETALL_LLPRT2018(LLRPT);


CREATE TABLE IF NOT EXISTS LL_DATA_REPORT(
			ID  INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
      PRO_ID VARCHAR(16) DEFAULT '' NOT NULL,
      USER_ID INT(11) DEFAULT 0 NOT NULL,
      ORG_ID  INT(11) DEFAULT 0 NOT NULL,
      ORDERTM TIMESTAMP DEFAULT '1991-01-01 00:00:00' NOT NULL,
      SUNMITNUM INT(11) DEFAULT 0 NOT NULL,
      SUCCNUM INT(11) DEFAULT 0 NOT NULL,
      FAILDNUM  INT(11) DEFAULT 0 NOT NULL,
      R1  VARCHAR(64) DEFAULT '' NOT NULL,
      R2  VARCHAR(64) DEFAULT '' NOT NULL,
      R3  VARCHAR(64) DEFAULT '' NOT NULL,
      R4  VARCHAR(64) DEFAULT '' NOT NULL,
      CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL
);



CREATE TABLE IF NOT EXISTS LL_STATUSRPT(
			ID  INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
			MOBILE  VARCHAR(16) DEFAULT '' NOT NULL,           
			PRODUCTID  VARCHAR(32) DEFAULT '' NOT NULL,
			LLRPT      VARCHAR(2) DEFAULT '' NOT NULL,
			ORDERTM    VARCHAR(16) DEFAULT '' NOT NULL,
			ERRCODE    VARCHAR(16) DEFAULT '' NOT NULL,
			ORDERNO    VARCHAR(64) DEFAULT '' NOT NULL,
			CREATETM   TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL

);

/**
#DROP TABLE LL_ORDER_TASK;
#DROP TABLE LL_PRODUCT;
#DROP TABLE LL_COMP_INFO;
#DROP TABLE LL_ORDER_DETAIL;
#DROP TABLE LL_ORDER_DETAIL2017
#DROP TABLE LL_ORDER_DETAIL2018
#DROP TABLE LL_DATA_REPORT;
**/


DELETE FROM LF_THIR_MENUCONTROL WHERE MENU_NUM = 28;
INSERT INTO LF_THIR_MENUCONTROL(MENU_NUM,TITLE,PRI_MENU,PRI_ORDER) SELECT 28,'企业流量',88,370 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_THIR_MENUCONTROL WHERE MENU_NUM=28 and PRI_MENU = 88 and PRI_ORDER = 370);
INSERT INTO LF_THIR_MENUCONTROL(MENU_NUM,TITLE,PRI_MENU,PRI_ORDER) SELECT 28,'企业流量',89,375 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_THIR_MENUCONTROL WHERE MENU_NUM=28 and PRI_MENU = 89 and PRI_ORDER = 375);
INSERT INTO LF_THIR_MENUCONTROL(MENU_NUM,TITLE,PRI_MENU,PRI_ORDER) SELECT 28,'企业流量',90,380 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_THIR_MENUCONTROL WHERE MENU_NUM=28 and PRI_MENU = 90 and PRI_ORDER = 380);
INSERT INTO LF_THIR_MENUCONTROL(MENU_NUM,TITLE,PRI_MENU,PRI_ORDER) SELECT 28,'企业流量',91,385 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_THIR_MENUCONTROL WHERE MENU_NUM=28 and PRI_MENU = 91 and PRI_ORDER = 385);
COMMIT;
INSERT INTO LF_REVIEWSWITCH(ID,SWITCH_TYPE,MSG_COUNT,INFO_TYPE,CORP_CODE) SELECT 8,1,2,7,100001 FROM DUAL WHERE NOT EXISTS(SELECT 1 FROM LF_REVIEWSWITCH WHERE ID = 8);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3000,88,1,'查看','6666-1000-0','流量套餐订购','流量订购','6666-1000','/ll_flowOrder.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3000);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3001,88,1,'查看','6666-1100-0','流量套餐同步','流量订购','6666-1100','/ll_flowSynchronize.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3001);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3002,89,1,'查看','6666-1200-0','套餐订购详情','数据查询','6666-1200','/ll_orderDetails.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3002);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3003,89,1,'查看','6666-1300-0','套餐订购任务查询','数据查询','6666-1300','/ll_packageOrderQuest.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3003);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3004,89,1,'查看','6666-1400-0','套餐订购历史查询','数据查询','6666-1400','/ll_orderHistoryQuest.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3004);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3005,89,1,'查看','6666-1500-0','短信提醒下行记录','数据查询','6666-1500','/ll_downRecord.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3005);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3006,89,1,'查看','6666-1600-0','短信提醒任务查询','数据查询','6666-1600','/ll_smsTaskQuest.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3006);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3007,89,1,'查看','6666-1700-0','短信提醒历史查询','数据查询','6666-1700','/ll_smsHistoryQuest.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3007);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3008,90,1,'查看','6666-1800-0','套餐订购统计报表','统计报表','6666-1800','/ll_orderReport.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3008);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3009,90,1,'查看','6666-1900-0','操作员统计报表','统计报表','6666-1900','/ll_operatorReport.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3009);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3010,90,1,'查看','6666-2000-0','机构统计报表','统计报表','6666-2000','/ll_mechanismReport.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3010);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3011,91,1,'查看','6666-2100-0','账号配置','账号管理','6666-2100','/ll_accountManage.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3011);

INSERT INTO LF_PRIVILEGE(PRIVILEGE_ID,RESOURCE_ID,OPERATE_ID,COMMENTS,PRIV_CODE,MENUNAME,MODNAME,MENUCODE,MENUSITE) SELECT 3012,8,1,'查看','1350-1260-0','流量审核','审批管理','1350-1260','/ll_flowReview.htm' FROM DUAL 
WHERE NOT EXISTS (SELECT 1 FROM LF_PRIVILEGE where PRIVILEGE_ID = 3012);

UPDATE LF_THIR_MENUCONTROL SET ZH_TW_TITLE = '企業流量',ZH_HK_TITLE = 'Enterprise Data' WHERE PRI_MENU IN (88,89,90,91);
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '流量套餐訂購' ,ZH_HK_MENUNAME = 'Data plan order' , ZH_TW_MODNAME = '流量訂購' , ZH_HK_MODNAME = 'Data ordering'  WHERE PRIVILEGE_ID = 3000;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '流量套餐同步' ,ZH_HK_MENUNAME = 'Synchronization' , ZH_TW_MODNAME = '流量訂購' , ZH_HK_MODNAME = 'Data ordering' WHERE PRIVILEGE_ID = 3001;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購詳情' ,ZH_HK_MENUNAME = 'Detail of order' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3002;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購任務查詢' ,ZH_HK_MENUNAME = 'Order task' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3003;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購歷史查詢' ,ZH_HK_MENUNAME = 'History of order' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3004;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '短信提醒下行記錄' ,ZH_HK_MENUNAME = 'SMS reminder record' , ZH_TW_MODNAME = '數據查詢' , ZH_HK_MODNAME = 'Data query' WHERE PRIVILEGE_ID = 3005;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '套餐訂購統計報表' ,ZH_HK_MENUNAME = ' Data plan statistics' , ZH_TW_MODNAME = '統計報表' , ZH_HK_MODNAME = 'Statistical report' WHERE PRIVILEGE_ID = 3008;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '操作員統計報表' ,ZH_HK_MENUNAME = 'Operator statistics' , ZH_TW_MODNAME = '統計報表' , ZH_HK_MODNAME = 'Statistical report' WHERE PRIVILEGE_ID = 3009;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '機構統計報表' ,ZH_HK_MENUNAME = 'Organization statistics' , ZH_TW_MODNAME = '統計報表' , ZH_HK_MODNAME = 'Statistical report' WHERE PRIVILEGE_ID = 3010;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '賬號配置' ,ZH_HK_MENUNAME = 'Settings ' , ZH_TW_MODNAME = '賬號管理' , ZH_HK_MODNAME = 'Account' WHERE PRIVILEGE_ID = 3011;
UPDATE LF_PRIVILEGE SET  ZH_TW_COMMENTS = '查看' , ZH_HK_COMMENTS = 'View' ,ZH_TW_MENUNAME = '流量審核' ,ZH_HK_MENUNAME = 'Data Audit' , ZH_TW_MODNAME = '審批管理' , ZH_HK_MODNAME = 'Approval' WHERE PRIVILEGE_ID = 3012;
COMMIT;

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3000);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3000);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3000 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3000);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3001);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3001);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3001);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3002 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3002);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3002 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3002);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3002 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3002);


INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3003 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3003);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3003 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3003);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3003 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3003);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3004 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3004);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3004 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3004);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3004 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3004);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3005 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3005);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3005 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3005);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3005 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3005);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3006 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3006);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3006 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3006);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3006 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3006);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3007 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3007);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3007 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3007);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3007 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3007);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3008 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3008);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3008 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3008);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3008 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3008);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3009 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3009);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3009 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3009);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3009 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3009);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3010 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3010);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3010 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3010);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3010 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3010);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3011 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3011);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3011 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3011);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3011 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3011);

INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 1,3012 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 1 AND PRIVILEGE_ID = 3012);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 2,3012 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 2 AND PRIVILEGE_ID = 3012);
INSERT INTO LF_IMPOWER(ROLE_ID,PRIVILEGE_ID) SELECT 4,3012 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_IMPOWER where ROLE_ID = 4 AND PRIVILEGE_ID = 3012);

INSERT INTO LF_REVIEWSWITCH(ID,SWITCH_TYPE,MSG_COUNT,INFO_TYPE,CORP_CODE) SELECT 8,1,2,7,100001 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM LF_REVIEWSWITCH WHERE ID = 8);

COMMIT;

DROP PROCEDURE IF EXISTS CREATE_LL_ORDER_DETAIL;
CREATE PROCEDURE CREATE_LL_ORDER_DETAIL()
BEGIN 
	select date_format(now(),'%Y')+1 into @v_time from dual;
	set @tableName = CONCAT("LL_ORDER_DETAIL",@v_time);
  set @v_createsql = CONCAT(" create table if not exists  ",@tableName," (ID  INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,MOBILE VARCHAR(16) DEFAULT '' NOT NULL,MSG VARCHAR(2048) DEFAULT '' NOT NULL,
BATCHID INT(11) DEFAULT 0 NOT NULL,ORDERNO VARCHAR(64) DEFAULT '' NOT NULL,LLRPT VARCHAR(32) DEFAULT '' NOT NULL,ERRCODE VARCHAR(20) DEFAULT '' NOT NULL,USER_ID INT(11) DEFAULT 0 NOT NULL,
ORG_ID  INT(11) DEFAULT 0 NOT NULL, PRO_ID INT(11) DEFAULT 0 NOT NULL,PRODUCTID VARCHAR(32) DEFAULT '' NOT NULL,ORDERTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,RPTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
UPDATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,CREATETM TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,STATUS	INT(11) DEFAULT 0 NOT NULL,REPORTDATE VARCHAR(16) DEFAULT '' NOT NULL",
", KEY ","INDEX_DETALL_MOBILE",@v_time," (MOBILE)",", KEY ","INDEX_DETALL_ORDERNO",@v_time," (ORDERNO)",", KEY ","INDEX_DETALL_USER_ID",@v_time," (USER_ID)",", KEY ","INDEX_DETALL_ORG_ID",@v_time," (ORG_ID)",
", KEY ","INDEX_DETALL_PRO_ID",@v_time," (PRO_ID)",", KEY ","INDEX_DETALL_REPORTDATE",@v_time," (REPORTDATE)",", KEY ","INDEX_DETALL_LLRPT",@v_time," (LLRPT)",") ENGINE=MyISAM ;"
);
	PREPARE create_table FROM @v_createsql;
	EXECUTE create_table;
END;

set global event_scheduler =1;

CREATE EVENT  IF NOT EXISTS EVENT_LL_ORDER_DETAIL  
ON SCHEDULE EVERY 1 YEAR STARTS DATE_ADD(DATE(CONCAT(YEAR(CURDATE()),'-',12,'-',1)),INTERVAL 1 HOUR)  
ON COMPLETION PRESERVE ENABLE  
DO CALL CREATE_LL_ORDER_DETAIL(); 

DROP PROCEDURE IF EXISTS `LF_PVERV0`;
DELIMITER ;;
CREATE DEFINER=`root`@`%` PROCEDURE `LF_PVERV0`(
    VERSIONSTR VARCHAR(32),
    DBVERSIONSTR VARCHAR(32),
    WBSVERSION VARCHAR(32),
    SPGATEVERSION VARCHAR(32),
    NUM INT,
    TOTALSTR INT
)
BEGIN
	/*EMP产品版本记录*/
	/*EMP-WEB*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,1000,VERSIONSTR,NOW(),NOW(),'EMP-WEB');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=VERSIONSTR WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
	END IF;
	/*EMP_GATEWAY*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=2000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,2000,WBSVERSION,NOW(),NOW(),'EMP_GATEWAY');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=WBSVERSION WHERE  PRODUCT_ID=1000 AND PROCESS_ID=2000;
	END IF;
	/*SMT_SPGATE*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION WHERE PRODUCT_ID=1000 AND PROCESS_ID=3000) THEN
		INSERT INTO LF_VERSION(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,3000,SPGATEVERSION,NOW(),NOW(),'SMT_SPGATE');
	ELSE
		UPDATE LF_VERSION SET UPDATETIME=NOW(),VERSION=SPGATEVERSION WHERE  PRODUCT_ID=1000 AND PROCESS_ID=3000;
	END IF;
	/*EMP产品版本历史记录*/
	/*EMP-WEB*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=VERSIONSTR AND PRODUCT_ID=1000 AND PROCESS_ID=1000) THEN
			INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO,ISRELEASE,VERSIONINFO)
			VALUES(1000,1000,VERSIONSTR,NOW(),NOW(),'EMP-WEB',1,'1.新增企业流量');
	ELSE
			UPDATE LF_VERSION_HIS SET UPDATETIME=NOW(),ISRELEASE=1,VERSIONINFO='1.新增企业流量' WHERE PRODUCT_ID=1000 AND PROCESS_ID=1000;
	END IF;
	/*EMP_GATEWAY*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=WBSVERSION AND PRODUCT_ID=1000 AND PROCESS_ID=2000) THEN
		INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,2000,WBSVERSION,NOW(),NOW(),'EMP_GATEWAY');
	ELSE
		UPDATE LF_VERSION_HIS SET UPDATETIME=NOW() WHERE  PRODUCT_ID=1000 AND PROCESS_ID=2000;
	END IF;
	/*SMT_SPGATE*/
	IF NOT EXISTS(SELECT * FROM LF_VERSION_HIS WHERE VERSION=SPGATEVERSION AND PRODUCT_ID=1000 AND PROCESS_ID=3000) THEN
		INSERT INTO LF_VERSION_HIS(PRODUCT_ID,PROCESS_ID,VERSION,UPDATETIME,CREATETIME,MEMO)
		VALUES(1000,3000,SPGATEVERSION,NOW(),NOW(),'SMT_SPGATE');
	ELSE
		UPDATE LF_VERSION_HIS SET UPDATETIME=NOW() WHERE  PRODUCT_ID=1000 AND PROCESS_ID=3000;
	END IF;
	IF NOT EXISTS(SELECT * FROM LF_DB_SCRIPT WHERE VERSION=DBVERSIONSTR AND CURRENT_NO=NUM AND TOTAL=TOTALSTR) THEN
		/*EMP产品数据库版本信息表*/
		INSERT INTO LF_DB_SCRIPT(VERSION,UPDATETIME,CREATETIME,CURRENT_NO,TOTAL,STATE,MEMO)
		VALUES(DBVERSIONSTR,NOW(),NOW(),NUM,TOTALSTR,2,'4号脚本');
	ELSE
		UPDATE LF_DB_SCRIPT SET STATE=2,UPDATETIME=NOW() WHERE  CURRENT_NO=NUM AND TOTAL=TOTALSTR;
	END IF;
END     
;; DELIMITER ;
CALL LF_PVERV0('7.0.0.395','7.00','8.4.10.163','6.1.23.316',3,3);
DROP PROCEDURE IF EXISTS `LF_PVERV0`;
   


